import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'te' | 'ta' | 'es' | 'ar';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', dir: 'ltr' },
  { code: 'es', label: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'ar', label: 'Arabic', nativeName: 'العربية', flag: '🇦🇪', dir: 'rtl' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav Tabs
    'nav.discover': 'Discover',
    'nav.shorts': 'Shorts',
    'nav.tactical': 'Tactical AI',
    'nav.stadium3d': '3D Stadium',
    'nav.analytics': 'Radar',
    'nav.rl': 'RL Agent',
    'nav.cybersecurity': 'Cyber Shield',
    'nav.athletes': 'Athletes',
    'nav.profile': 'Profile',
    'nav.login': 'Login / Register',
    'nav.logout': 'Sign Out',
    'nav.sparks': 'Sparks',
    'nav.live_mesh': 'ICC LIVE TOURNAMENT MESH',
    'nav.over_live': 'OVER 14.3 LIVE',

    // 3D Stadium
    'stadium.title': 'Hyper-Realistic 3D WebGL Cricket Stadium',
    'stadium.subtitle': 'Volumetric Lighting, Procedural Textures & Physics Engine',
    'stadium.desc': 'Featuring 4 floodlight volumetric beams, procedural mower turf, weathered clay pitch scuffs, animated LED sponsor hoardings, sight screens, and flying bails physics.',
    'stadium.play': 'Play',
    'stadium.pause': 'Pause',
    'stadium.reset': 'Reset',
    'stadium.cam_broadcast': 'Broadcast',
    'stadium.cam_batter': 'Batter POV',
    'stadium.cam_hawkeye': 'Hawk-Eye',
    'stadium.cam_topdown': 'Top-Down',
    'stadium.cam_stump': 'Stump Cam',
    'stadium.cam_drone': 'Drone Orbit',
    'stadium.cam_ballfollow': 'Ball Follow',
    'stadium.delivery': 'Delivery:',
    'stadium.del_seam': '142 km/h Seam',
    'stadium.del_spin': '86 km/h Spin',
    'stadium.del_yorker': '148 km/h Yorker',
    'stadium.shot': 'Shot:',
    'stadium.shot_cover': 'Cover Drive (6)',
    'stadium.shot_pull': 'Pull Shot (4)',
    'stadium.shot_straight': 'Straight Drive (4)',
    'stadium.shot_upper': 'Upper Cut (6)',
    'stadium.shot_wicket': 'Wicket ⚡',
    'stadium.lighting': 'Lighting:',
    'stadium.light_day': 'Day',
    'stadium.light_sunset': 'Sunset',
    'stadium.light_night': 'Night',
    'stadium.trail': 'Hawk-Eye Trail',
    'stadium.flashes': 'Crowd Flashes',
    'stadium.in_flight': 'IN FLIGHT',
    'stadium.contact_made': 'CONTACT MADE',
    'stadium.ready': 'READY',

    // Tactical AI Co-Pilot
    'tactical.badge': 'AI Tactical Intelligence & Multi-Model Ensemble',
    'tactical.title': 'Tactical Co-Pilot & AI Model Studio',
    'tactical.subtitle': 'Trained on 2,896 match files (7,119 tactical states) and 90,308 player career profiles with 0.9988 ROC-AUC calibration.',
    'tactical.tab_copilot': 'Co-Pilot & Radar',
    'tactical.tab_matchup': 'Matchup Matrix',
    'tactical.tab_inplay': 'In-Play Win Sim',
    'tactical.tab_studio': 'AI Studio & Scenarios',
    'tactical.field_radar': 'Dynamic Field Placement Visualizer',
    'tactical.suggested_questions': 'AI Suggested Tactical Questions',
    'tactical.click_analyze': 'Click to Analyze',
    'tactical.ask_placeholder': 'Ask tactical AI (e.g. why did the captain set a deep slip?)...',
    'tactical.speak_guidance': 'Speak Guidance',
    'tactical.listen_review': 'Listen to Over Review',
    'tactical.threat_high': 'HIGH THREAT',
    'tactical.threat_vulnerable': 'VULNERABLE',
    'tactical.threat_neutral': 'NEUTRAL',
    'tactical.threat_favorable': 'FAVORABLE',

    // Data Analytics
    'analytics.badge': 'Big Data Cricket Analytics & Intelligence Platform',
    'analytics.title': 'Data Analysis, Match Statistics & ML Telemetry',
    'analytics.subtitle': 'Grounded in 2,896 match files (7,119 over snapshots), 90,308 player career records, and 16,666 demographic profiles.',
    'analytics.tab_data': 'Data Analysis',
    'analytics.tab_ml': 'ML Predictor',
    'analytics.tab_players': 'Top Players (500)',
    'analytics.tab_matches': 'Recent Matches',
    'analytics.tab_charts': 'Live Charts',
    'analytics.kpi_matches': 'Matches Mined',
    'analytics.kpi_states': 'Tactical States',
    'analytics.kpi_players': 'Player Records',
    'analytics.kpi_accuracy': 'GB Accuracy',
    'analytics.kpi_t20_par': 'T20 Avg 1st Inns',
    'analytics.kpi_odi_par': 'ODI Avg 1st Inns',
    'analytics.team_power_title': 'Highest-Rated International & Franchise Teams',
    'analytics.phase_quantiles_title': 'Phase Scoring Quantiles (Floor vs Ceiling)',
    'analytics.leaderboard_title': 'Composite Player Impact (CPI) Leaderboard',
    'analytics.predict_win': 'Win Probability',
    'analytics.projected_score': 'Projected 1st Innings',
    'analytics.search_player': 'Search by player or country...',

    // General
    'common.live': 'LIVE',
    'common.all': 'All',
    'common.runs': 'Runs',
    'common.wickets': 'Wickets',
    'common.strike_rate': 'Strike Rate',
    'common.overs': 'Overs',
    // Tournament Ribbon & Brand
    'ribbon.tournament': "ICC Women's T20 World Cup Final",
    'ribbon.venue': 'Dubai International Stadium',
    'ribbon.fans_synced': '8.4M Fans Synced Live',
    'ribbon.streams': '12 Regional AI Streams',
    'ribbon.zerotrust': 'Zero-Trust Guard: Active',
    'ribbon.sync_langs': '6 Languages Synchronized',
    'brand.tagline': 'Multimodal Canon • 3D Stadium • Live Fandom',

    // Hero Section
    'hero.badge': 'GENESIS V2.4 CANON PROTOCOL • DUBAI AI SHOWCASE',
    'hero.title_pre': 'Co-Create',
    'hero.title_gradient': 'Infinite Canon',
    'hero.title_post': 'With AI & Your Fandom',
    'hero.desc': "Step into an ethereal collaborative realm where live women's cricket telemetry ignites autonomous vertical micro-stories, 3D stadium physics, and conversational tactical co-piloting.",
    'hero.cta_dashboard': 'Launch Live Dashboard',
    'hero.cta_auth': 'Sign In / Lorekeeper Access',

    // Featured Multimodal Storyboards
    'featured.title': 'Featured Multimodal Storyboards',
    'featured.subtitle': 'Autonomous video-to-manga adaptations generated in real-time',
    'featured.view_all': 'View All (28)',
    'featured.card1_title': "The Sharjah Mirage: Smriti's 140km/h Counter-Assault",
    'featured.card1_desc': 'Reconstructed from over 18 ball telemetry. Shonen manga aesthetic generated with Stable Diffusion XL LoRA and Hindi commentary synthesis.',
    'featured.card1_watch': 'Watch Story',
    'featured.card2_title': "Harmanpreet's Leg-Side Trap: Probability Breakdown",
    'featured.card2_desc': 'Deep Q-Learning MDP analysis explaining the placement of backward square leg and deep mid-wicket against Sophie Ecclestone.',
    'featured.card2_inspect': 'Inspect Replay',
    'featured.card3_title': "Kathmandu to Lord's: Puja Mahato's 5-Wicket Odyssey",
    'featured.card3_desc': 'Community-funded story highlighting Nepal U-19 fast bowler with direct micro-tipping passport integration.',
    'featured.card3_tip': 'Tip Athlete',

    // Live Co-Creation Arenas
    'arenas.title': 'Live Co-Creation Arenas',
    'arenas.subtitle': 'Real-time multiplayer rooms synthesizing match narratives',
    'arenas.active_badge': '3 ARENAS ACTIVE',
    'arenas.room1_title': 'Cyber-Valkyrie Writers',
    'arenas.room1_sub': 'Match: IND-W vs AUS-W (Finals)',
    'arenas.room1_creators': '84 Creators',
    'arenas.room1_scene': "Current Scene: Harmanpreet's reverse-sweep in 19th over",
    'arenas.room2_title': 'Tactical Analysis Guild',
    'arenas.room2_sub': 'Field Geometry & Spin Trajectories',
    'arenas.room2_creators': '126 Creators',
    'arenas.room2_scene': 'Current Scene: PINN aerodynamic drift on 62km/h leg break',
    'arenas.room3_title': 'Grassroots Spotlight Studio',
    'arenas.room3_sub': 'Nepal, Thailand & Scotland Stars',
    'arenas.room3_creators': '62 Creators',
    'arenas.room3_scene': 'Current Scene: Crowdsourced grant milestone 5,000 Sparks',
    'arenas.join_btn': 'Join Co-Creation Session',

    // Canon Governance Poll
    'poll.badge': 'CANON GOVERNANCE PROPOSAL #88',
    'poll.closes': 'CLOSES IN 04:18:22',
    'poll.title': 'Tactical Dilemma: What should captain Harmanpreet bowl in Over 19.4?',
    'poll.desc': 'The winning choice determines the generated shonen anime climax and unlocks double fan Sparks for tactical voters.',
    'poll.opt1': 'Deploy the Quantum Googly Trap',
    'poll.opt2': 'Hold standard off-stump length corridor',
    'poll.opt3': 'Bring in boundary sweeper for slog sweep',
    'poll.total_votes': 'Total community votes: 3,489',
    'poll.sparks_reward': '+50 Sparks Upon Voting',

    // Multilingual AI Commentary Player
    'audio.badge': 'MULTILINGUAL AI COMMENTARY SYNTH',
    'audio.dialects': '12 DIALECTS READY',
    'audio.title': 'Bengali & Tamil Voice Synthesis: "The Six That Shook Sharjah"',
    'audio.desc': 'Listen to the neural voice clone adapting intensity, crowd roar acoustics, and pitch cadence dynamically based on win probability shifts.',
    'audio.preview': 'Preview Neural Voice',
    'audio.pause': 'Pause Stream',
    'audio.latency': 'Latency: 280ms',

    // Pillars of Creation
    'pillars.tag': 'Pillars of Creation',
    'pillars.title': 'Multi-Threaded AI Architecture',
    'pillars.p1_title': 'Multimodal Story Engine',
    'pillars.p1_desc': 'Text, voice commentary, vertical video reframing & live HUD telemetry synthesized synchronously in under 45 seconds.',
    'pillars.p2_title': 'Collaborative Tactical Co-Pilot',
    'pillars.p2_desc': 'Demystifies captaincy field placements with conversational AI, dynamic 2D field radar, and 3D WebGL physics.',
    'pillars.p3_title': 'Grassroots Future Stars Fund',
    'pillars.p3_desc': 'Fans pledge micro-tokens to female athletes with 15% ring-fenced to provide kits and travel for associate nation academies.',

    // Relic Codex
    'codex.tag': 'ARCHIVES & RELIC NODES',
    'codex.title': 'Canonical Sport Artefacts & Timeline Trees',
    'codex.total': 'Total Artifacts: 1,420',
    'codex.card1_title': 'What-If Branch #44',
    'codex.card1_desc': 'Alternative history where Sophie Devine opened the bowling with leg-spin.',
    'codex.card2_title': 'Hawk-Eye Spin Relic',
    'codex.card2_desc': '3D mathematical trajectory token signed by ICC telemetric feed.',
    'codex.card3_title': 'Clutch Over Master',
    'codex.card3_desc': 'Fan badge minted for correctly forecasting the penultimate over yorker.',
    'codex.card4_title': 'Quantum Physics Node',
    'codex.card4_desc': 'Run physics-informed neural network tests on any historical delivery.',

    // Community Stats
    'community.creators': '140,000+ Fan Co-Creators Globally',
    'community.active_desc': "Active across 850+ canonical women's cricket tournaments & story arcs",
    'community.verified': 'Verified ICC Canon Ledger #8802',
    'community.enter': 'Enter Now',

    // Shorts & Vertical Reels
    'shorts.badge': 'Autonomous Multimodal Highlight Pipeline',
    'shorts.title': 'Vertical Micro-Narratives & Multi-Language Synthesis',
    'shorts.desc': 'Raw ICC broadcast video converted into 9:16 vertical storytelling reels in under 45 seconds with automated ball telemetry, tactical annotations, and commentary in 12+ languages.',
    'shorts.edge_ingestion': 'Edge Ingestion: 38s',
    'shorts.tab_shorts': '9:16 Shorts',
    'shorts.tab_long': '16:9 Broadcast',
    'shorts.exit_velocity': 'Exit Velocity',
    'shorts.launch_angle': 'Launch Angle',
    'shorts.distance': 'Distance',
    'shorts.win_prob_delta': 'Win Prob Delta',
    'shorts.tactical_breakdown': 'Tactical Breakdown',
    'shorts.ai_commentary': 'AI Neural Commentary',
    'shorts.play_audio': 'Listen in Voice',
    'shorts.stop_audio': 'Stop Voice',
    'shorts.share': 'Share Reel',
    'shorts.all': 'All',
    'shorts.cat_masterclass': 'Masterclass',
    'shorts.cat_pace': 'Pace Attack',
    'shorts.cat_clutch': 'Clutch Defense',
    'shorts.cat_captaincy': 'Captaincy',
    'shorts.cat_fielding': 'Fielding',
    'shorts.cat_spin': 'Spin Magic',
    'shorts.cat_power': 'Power Hitting',
    'shorts.cat_death': 'Death Bowling',
    'shorts.cat_grassroots': 'Grassroots Talent',
    'shorts.cat_wicketkeeping': 'Wicketkeeping',
    'shorts.cat_final': 'Final Moments',

    // Athlete Digital Passport
    'athletes.badge': 'Empowerment & Grassroots Inclusivity',
    'athletes.title': 'Athlete Digital Passport & Micro-Sponsorship Hub',
    'athletes.desc': 'Bridging the grassroots funding divide. Fans back women athletes and academy talent directly, earning verified digital credentials while funding gear, travel, and training clinics.',
    'athletes.balance': 'Your Fan Balance',
    'athletes.tokens': 'Fan Tokens',
    'athletes.back_athlete': 'Back with 50 Tokens',
    'athletes.backed_success': 'Athlete Backed! +50 Sparks',
    'athletes.funded': 'Funded',
    'athletes.target': 'Target',
    'athletes.strike_rate': 'Strike Rate',
    'athletes.matches': 'Matches',
    'athletes.wickets': 'Wickets',
    'athletes.journey': 'Player Journey',
    'athletes.fund_purpose': 'Grant Purpose',

    // Deep RL Simulator
    'rl.badge': 'Deep Q-Learning & Policy Gradient Architecture',
    'rl.title': 'Deep Reinforcement Learning Pitch Simulator',
    'rl.desc': 'Simulating captaincy decisions with Markov Decision Process (MDP) state-space policies trained on thousands of match scenarios.',
    'rl.train_step': 'Run RL Optimization Step (+50 Epochs)',
    'rl.training': 'Optimizing Q-Policy...',
    'rl.episodes': 'Training Episodes',
    'rl.reward': 'Cumulative Reward',
    'rl.epsilon': 'Exploration Rate (ε)',
    'rl.confidence': 'Policy Confidence',
    'rl.optimal_action': 'Optimal Recommended Action',
    'rl.batter_type': 'Batter Profile',
    'rl.bowler_type': 'Bowler Profile',
    'rl.phase': 'Match Phase',

    // Cyber Security Shield
    'cyber.badge': 'Zero-Trust Security & HMAC Cryptographic Mesh',
    'cyber.title': 'Cyber Shield & AI Prompt Defense Center',
    'cyber.desc': 'Protecting real-time broadcast telemetry and fan governance from adversarial injection, data tampering, and malicious model jailbreaks.',
    'cyber.firewall_title': 'Adversarial Prompt Injection Firewall',
    'cyber.test_prompt': 'Input Query to Test Firewall',
    'cyber.inspect_btn': 'Inspect with Zero-Trust Guard',
    'cyber.tamper_telemetry': 'Simulate Tampered Telemetry',
    'cyber.restore_telemetry': 'Restore Cryptographic Signature',
    'cyber.clean': 'CLEAN — AUTHENTICATED',
    'cyber.blocked': 'BLOCKED — ADVERSARIAL THREAT DETECTED',
    'cyber.signature_valid': 'Cryptographic HMAC Signature Verified',
    'cyber.signature_invalid': 'TAMPERING DETECTED: Signature Mismatch',

    // User Profile
    'profile.title': 'Fan Co-Creator Synapse Profile',
    'profile.handle': 'Lorekeeper ID',
    'profile.sparks_balance': 'Fan Sparks Balance',
    'profile.credentials': 'Verified ICC Credentials',
    'profile.achievements': 'Unlocked Achievements',
    'profile.connected': 'Synapse Connected',
    'profile.logout': 'Sign Out of FanVerse',

    // Authentication Modal
    'auth.title': 'AURA Lorekeeper Access',
    'auth.subtitle': 'Sign in with cryptographic keypass or email verification',
    'auth.email_label': 'Creator Email or Web3 Handle',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'Generate Verification Cipher',
    'auth.otp_title': 'Enter 6-Digit Verification Cipher',
    'auth.otp_desc': 'A single-use cryptographic token was dispatched to your handle.',
    'auth.biometric': 'Use Biometric Passkey',
    'auth.verifying': 'Verifying Cryptographic Cipher...',
    'auth.success': 'Authentication Verified! Entering FanVerse...',
    'auth.back': 'Back',
  },

  hi: {
    // Nav Tabs
    'nav.discover': 'खोजें',
    'nav.shorts': 'शॉर्ट्स',
    'nav.tactical': 'रणनीतिक AI',
    'nav.stadium3d': '3D स्टेडियम',
    'nav.analytics': 'रडार',
    'nav.rl': 'RL एजेंट',
    'nav.cybersecurity': 'साइबर शील्ड',
    'nav.athletes': 'एथलीट',
    'nav.profile': 'प्रोफाइल',
    'nav.login': 'लॉग इन / साइन अप',
    'nav.logout': 'लॉग आउट',
    'nav.sparks': 'स्पार्क्स',
    'nav.live_mesh': 'आईसीसी लाइव टूर्नामेंट मेश',
    'nav.over_live': 'ओवर 14.3 लाइव',

    // 3D Stadium
    'stadium.title': 'अति-यथार्थवादी 3D WebGL क्रिकेट स्टेडियम',
    'stadium.subtitle': 'वॉल्यूमेट्रिक लाइटिंग, प्रोसीजरल टेक्सचर और भौतिकी इंजन',
    'stadium.desc': '4 फ्लडलाइट वॉल्यूमेट्रिक बीम, घास की धारियां, मिट्टी की पिच, एनिमेटेड एलईडी होर्डिंग और उड़ती गिल्लियां।',
    'stadium.play': 'चलाएं',
    'stadium.pause': 'रोकें',
    'stadium.reset': 'रीसेट',
    'stadium.cam_broadcast': 'प्रसारण',
    'stadium.cam_batter': 'बल्लेबाज POV',
    'stadium.cam_hawkeye': 'हॉक-आई',
    'stadium.cam_topdown': 'ऊपर से दृश्य',
    'stadium.cam_stump': 'स्टंप कैमरा',
    'stadium.cam_drone': 'ड्रोन ऑर्बिट',
    'stadium.cam_ballfollow': 'गेंद ट्रैकिंग',
    'stadium.delivery': 'गेंदबाजी:',
    'stadium.del_seam': '142 किमी/घंटा सीम',
    'stadium.del_spin': '86 किमी/घंटा स्पिन',
    'stadium.del_yorker': '148 किमी/घंटा यॉर्कर',
    'stadium.shot': 'शॉट:',
    'stadium.shot_cover': 'कवर ड्राइव (6)',
    'stadium.shot_pull': 'पुल शॉट (4)',
    'stadium.shot_straight': 'स्ट्रेट ड्राइव (4)',
    'stadium.shot_upper': 'अपर कट (6)',
    'stadium.shot_wicket': 'विकेट गिरा ⚡',
    'stadium.lighting': 'रोशनी:',
    'stadium.light_day': 'दिन',
    'stadium.light_sunset': 'सूर्यास्त',
    'stadium.light_night': 'रात',
    'stadium.trail': 'हॉक-आई ट्रेल',
    'stadium.flashes': 'दर्शकों के फ्लैश',
    'stadium.in_flight': 'हवा में',
    'stadium.contact_made': 'संपर्क हुआ',
    'stadium.ready': 'तैयार',

    // Tactical AI Co-Pilot
    'tactical.badge': 'AI सामरिक बुद्धिमत्ता और मल्टी-मॉडल पहनावा',
    'tactical.title': 'रणनीतिक सह-पायलट और AI मॉडल स्टूडियो',
    'tactical.subtitle': '2,896 मैचों (7,119 सामरिक स्थितियों) और 90,308 खिलाड़ी प्रोफाइलों पर प्रशिक्षित।',
    'tactical.tab_copilot': 'सह-पायलट और रडार',
    'tactical.tab_matchup': 'मुकाबला मैट्रिक्स',
    'tactical.tab_inplay': 'लाइव मैच सिमुलेटर',
    'tactical.tab_studio': 'AI स्टूडियो और परिदृश्य',
    'tactical.field_radar': 'गतिशील फील्ड प्लेसमेंट विज़ुअलाइज़र',
    'tactical.suggested_questions': 'AI सुझाए गए रणनीतिक सवाल',
    'tactical.click_analyze': 'विश्लेषण के लिए क्लिक करें',
    'tactical.ask_placeholder': 'रणनीतिक सवाल पूछें (उदा. कप्तान ने डीप स्लिप क्यों रखी?)...',
    'tactical.speak_guidance': 'रणनीति सुनें',
    'tactical.listen_review': 'ओवर समीक्षा सुनें',
    'tactical.threat_high': 'उच्च खतरा',
    'tactical.threat_vulnerable': 'संवेदनशील',
    'tactical.threat_neutral': 'तटस्थ',
    'tactical.threat_favorable': 'अनुकूल',

    // Data Analytics
    'analytics.badge': 'बिग डेटा क्रिकेट एनालिटिक्स और इंटेलिजेंस प्लेटफॉर्म',
    'analytics.title': 'डेटा विश्लेषण, मैच सांख्यिकी और ML टेलीमेट्री',
    'analytics.subtitle': '2,896 मैच फाइलों, 90,308 खिलाड़ियों के रिकॉर्ड और 16,666 प्रोफाइलों पर आधारित।',
    'analytics.tab_data': 'डेटा विश्लेषण',
    'analytics.tab_ml': 'ML भविष्यवक्ता',
    'analytics.tab_players': 'शीर्ष खिलाड़ी (500)',
    'analytics.tab_matches': 'हालिया मैच',
    'analytics.tab_charts': 'लाइव चार्ट्स',
    'analytics.kpi_matches': 'विश्लेषित मैच',
    'analytics.kpi_states': 'सामरिक स्थितियां',
    'analytics.kpi_players': 'खिलाड़ी रिकॉर्ड',
    'analytics.kpi_accuracy': 'GB सटीकता',
    'analytics.kpi_t20_par': 'T20 औसत स्कोर',
    'analytics.kpi_odi_par': 'ODI औसत स्कोर',
    'analytics.team_power_title': 'शीर्ष रेटेड अंतर्राष्ट्रीय और फ्रैंचाइज़ी टीमें',
    'analytics.phase_quantiles_title': 'चरण स्कोरिंग अपेक्षाएं (न्यूनतम बनाम अधिकतम)',
    'analytics.leaderboard_title': 'समग्र खिलाड़ी प्रभाव (CPI) लीडरबोर्ड',
    'analytics.predict_win': 'जीत की संभावना',
    'analytics.projected_score': 'अनुमानित पहली पारी स्कोर',
    'analytics.search_player': 'खिलाड़ी या देश द्वारा खोजें...',

    // General
    'common.live': 'लाइव',
    'common.all': 'सभी',
    'common.runs': 'रन',
    'common.wickets': 'विकेट',
    'common.strike_rate': 'स्ट्राइक रेट',
    // Tournament Ribbon & Brand
    'ribbon.tournament': 'आईसीसी महिला टी20 विश्व कप फाइनल',
    'ribbon.venue': 'दुबई अंतर्राष्ट्रीय स्टेडियम',
    'ribbon.fans_synced': '8.4M प्रशंसक लाइव जुड़े',
    'ribbon.streams': '12 क्षेत्रीय AI स्ट्रीम्स',
    'ribbon.zerotrust': 'जीरो-ट्रस्ट शील्ड: सक्रिय',
    'ribbon.sync_langs': '6 भाषाएँ समन्वयित',
    'brand.tagline': 'मल्टीमॉडल कैनन • 3D स्टेडियम • लाइव फैंस',

    // Hero Section
    'hero.badge': 'जेनेसिस V2.4 कैनन प्रोटोकॉल • दुबई AI शोकेस',
    'hero.title_pre': 'सह-निर्माण करें',
    'hero.title_gradient': 'अनंत कैनन',
    'hero.title_post': 'AI और अपने क्रिकेट फैंस के साथ',
    'hero.desc': 'एक ऐसे जीवंत सहयोगी मंच में प्रवेश करें जहां महिला क्रिकेट का लाइव डेटा स्वचालित वर्टिकल माइक्रो-कहानियों, 3D स्टेडियम भौतिकी और संवादात्मक सामरिक AI को शक्ति देता है।',
    'hero.cta_dashboard': 'लाइव डैशबोर्ड शुरू करें',
    'hero.cta_auth': 'साइन इन / लोरकीपर एक्सेस',

    // Featured Multimodal Storyboards
    'featured.title': 'विशेष मल्टीमॉडल स्टोरीबोर्ड्स',
    'featured.subtitle': 'वास्तविक समय में उत्पन्न स्वचालित वीडियो-टू-मांगा रूपांतरण',
    'featured.view_all': 'सभी देखें (28)',
    'featured.card1_title': 'शारजाह का चमत्कार: स्मृति का 140 किमी/घंटा का जवाबी हमला',
    'featured.card1_desc': '18वें ओवर की बॉल टेलीमेट्री से पुनर्निर्मित। स्टेबल डिफ्यूजन XL LoRA और हिंदी कमेंट्री सिंथेसिस के साथ शोनेन मंगा शैली।',
    'featured.card1_watch': 'कहानी देखें',
    'featured.card2_title': 'हरमनप्रीत का लेग-साइड जाल: संभावना विश्लेषण',
    'featured.card2_desc': 'डीप Q-लर्निंग विश्लेषण जो सोफी एक्लेस्टोन के खिलाफ बैकवर्ड स्क्वायर लेग और डीप मिड-विकेट की फील्डिंग को समझाता है।',
    'featured.card2_inspect': 'रीप्ले जांचें',
    'featured.card3_title': 'काठमांडू से लॉर्ड्स: पूजा महतो की 5-विकेट ओडिसी',
    'featured.card3_desc': 'नेपाल की अंडर-19 तेज गेंदबाज को सम्मानित करने वाली कम्युनिटी-फंडेड कहानी।',
    'featured.card3_tip': 'खिलाड़ी को टिप दें',

    // Live Co-Creation Arenas
    'arenas.title': 'लाइव सह-निर्माण अखाड़े',
    'arenas.subtitle': 'मैच की कहानियों को संश्लेषित करने वाले वास्तविक समय के मल्टीप्लेयर रूम',
    'arenas.active_badge': '3 अखाड़े सक्रिय',
    'arenas.room1_title': 'साइबर-वाल्किरी लेखक',
    'arenas.room1_sub': 'मैच: IND-W बनाम AUS-W (फाइनल)',
    'arenas.room1_creators': '84 रचनाकार',
    'arenas.room1_scene': 'वर्तमान दृश्य: 19वें ओवर में हरमनप्रीत का रिवर्स-स्वीप',
    'arenas.room2_title': 'रणनीतिक विश्लेषण गिल्ड',
    'arenas.room2_sub': 'फील्ड ज्यामिति और स्पिन प्रक्षेपवक्र',
    'arenas.room2_creators': '126 रचनाकार',
    'arenas.room2_scene': 'वर्तमान दृश्य: 62 किमी/घंटा लेग ब्रेक पर PINN एरोडायनामिक ड्रिफ्ट',
    'arenas.room3_title': 'ग्रासरूट्स स्पॉटलाइट स्टूडियो',
    'arenas.room3_sub': 'नेपाल, थाईलैंड और स्कॉटलैंड के सितारे',
    'arenas.room3_creators': '62 रचनाकार',
    'arenas.room3_scene': 'वर्तमान दृश्य: क्राउडसोर्स फंड मील का पत्थर 5,000 स्पार्क्स',
    'arenas.join_btn': 'सत्र में शामिल हों',

    // Canon Governance Poll
    'poll.badge': 'कैनन शासन प्रस्ताव #88',
    'poll.closes': 'समाप्त होने में 04:18:22 शेष',
    'poll.title': 'रणनीतिक दुविधा: कप्तान हरमनप्रीत को 19.4 ओवर में क्या गेंद फेंकनी चाहिए?',
    'poll.desc': 'जीतने वाला विकल्प उत्पन्न होने वाले क्लाइमेक्स का फैसला करता है और वोटर्स के लिए दोगुने स्पार्क्स अनलॉक करता है।',
    'poll.opt1': 'क्वांटम गुगली जाल बिछाएं',
    'poll.opt2': 'ऑफ-स्टंप के बाहर मानक गुड लेंथ रखें',
    'poll.opt3': 'स्लॉग स्वीप रोकने के लिए बाउंड्री स्वीपर लाएं',
    'poll.total_votes': 'कुल सामुदायिक वोट: 3,489',
    'poll.sparks_reward': 'वोट करने पर +50 स्पार्क्स',

    // Multilingual AI Commentary Player
    'audio.badge': 'बहुभाषी AI कमेंट्री सिंथेसिस',
    'audio.dialects': '12 बोलियां तैयार',
    'audio.title': 'बंगाली और तमिल आवाज सिंथेसिस: "वह छक्का जिसने शारजाह हिला दिया"',
    'audio.desc': 'जीत की संभावना के बदलाव के आधार पर तीव्रता और पिच तालमेल को गतिशील रूप से अनुकूलित करने वाले न्यूरल वॉइस को सुनें।',
    'audio.preview': 'न्यूरल आवाज सुनें',
    'audio.pause': 'स्ट्रीम रोकें',
    'audio.latency': 'विलंबता: 280ms',

    // Pillars of Creation
    'pillars.tag': 'सृजन के स्तंभ',
    'pillars.title': 'मल्टी-थ्रेडेड AI आर्किटेक्चर',
    'pillars.p1_title': 'मल्टीमॉडल स्टोरी इंजन',
    'pillars.p1_desc': 'टेक्स्ट, वॉइस कमेंट्री, वर्टिकल वीडियो रिफ्रेमिंग और लाइव HUD टेलीमेट्री 45 सेकंड में तैयार।',
    'pillars.p2_title': 'सहयोगी सामरिक सह-पायलट',
    'pillars.p2_desc': 'संवादात्मक AI, डायनामिक 2D फील्ड रडार और 3D WebGL भौतिकी के साथ कप्तानी फील्डिंग को आसान बनाता है।',
    'pillars.p3_title': 'ग्रासरूट्स फ्यूचर स्टार्स फंड',
    'pillars.p3_desc': 'प्रशंसक महिला एथलीटों को माइक्रो-टोकन समर्पित करते हैं, जिसमें से 15% एसोसिएट देशों की अकादमियों के लिए सुरक्षित है।',

    // Relic Codex
    'codex.tag': 'अभिलेखागार और अवशेष',
    'codex.title': 'कैनोनिकल स्पोर्ट्स कलाकृतियां और समयरेखाएं',
    'codex.total': 'कुल कलाकृतियां: 1,420',
    'codex.card1_title': 'व्हाट-इफ शाखा #44',
    'codex.card1_desc': 'वैकल्पिक इतिहास जहां सोफी डिवाइन ने लेग-स्पिन के साथ गेंदबाजी की शुरुआत की।',
    'codex.card2_title': 'हॉक-आई स्पिन अवशेष',
    'codex.card2_desc': 'आईसीसी टेलीमेट्रिक फीड द्वारा हस्ताक्षरित 3D गणितीय प्रक्षेपवक्र टोकन।',
    'codex.card3_title': 'क्लच ओवर मास्टर',
    'codex.card3_desc': '19वें ओवर के यॉर्कर की सही भविष्यवाणी करने पर प्रशंसकों को दिया जाने वाला बैज।',
    'codex.card4_title': 'क्वांटम भौतिकी नोड',
    'codex.card4_desc': 'किसी भी ऐतिहासिक गेंद पर भौतिकी-सूचित न्यूरल नेटवर्क परीक्षण चलाएं।',

    // Community Stats
    'community.creators': 'दुनिया भर में 140,000+ सह-रचनाकार',
    'community.active_desc': '850+ कैनोनिकल महिला क्रिकेट टूर्नामेंटों और कहानियों में सक्रिय',
    'community.verified': 'सत्यापित ICC कैनन लेज़र #8802',
    'community.enter': 'अभी प्रवेश करें',

    // Shorts & Vertical Reels
    'shorts.badge': 'स्वायत्त मल्टीमॉडल हाइलाइट पाइपलाइन',
    'shorts.title': 'वर्टिकल माइक्रो-कहानियां और बहुभाषी आवाज संश्लेषण',
    'shorts.desc': '45 सेकंड से भी कम समय में आईसीसी प्रसारण वीडियो को 9:16 वर्टिकल रील्स में बदलें, जिसमें स्वचालित गेंद टेलीमेट्री और 12+ भाषाओं में कमेंट्री शामिल है।',
    'shorts.edge_ingestion': 'एज अंतर्ग्रहण: 38s',
    'shorts.tab_shorts': '9:16 शॉर्ट्स',
    'shorts.tab_long': '16:9 प्रसारण',
    'shorts.exit_velocity': 'निकास गति',
    'shorts.launch_angle': 'लॉन्च कोण',
    'shorts.distance': 'दूरी',
    'shorts.win_prob_delta': 'जीत संभावना बदलाव',
    'shorts.tactical_breakdown': 'रणनीतिक विश्लेषण',
    'shorts.ai_commentary': 'एआई न्यूरल कमेंट्री',
    'shorts.play_audio': 'आवाज में सुनें',
    'shorts.stop_audio': 'आवाज रोकें',
    'shorts.share': 'रील साझा करें',
    'shorts.all': 'सभी',
    'shorts.cat_masterclass': 'मास्टरक्लास',
    'shorts.cat_pace': 'तेज आक्रमण',
    'shorts.cat_clutch': 'संकटमोचक रक्षा',
    'shorts.cat_captaincy': 'कप्तानी',
    'shorts.cat_fielding': 'क्षेत्ररक्षण',
    'shorts.cat_spin': 'स्पिन जादू',
    'shorts.cat_power': 'पावर हिटिंग',
    'shorts.cat_death': 'डेथ ओवर बॉलिंग',
    'shorts.cat_grassroots': 'जमीनी प्रतिभा',
    'shorts.cat_wicketkeeping': 'विकेटकीपिंग',
    'shorts.cat_final': 'अंतिम क्षण',

    // Athlete Digital Passport
    'athletes.badge': 'सशक्तिकरण और जमीनी स्तर पर समावेशन',
    'athletes.title': 'एथलीट डिजिटल पासपोर्ट और माइक्रो-प्रायोजन केंद्र',
    'athletes.desc': 'जमीनी स्तर पर फंडिंग की खाई को पाटना। प्रशंसक सीधे महिला एथलीटों का समर्थन करते हैं, डिजिटल क्रेडेंशियल्स अर्जित करते हैं और किट तथा यात्रा का वित्तपोषण करते हैं।',
    'athletes.balance': 'आपका फैन बैलेंस',
    'athletes.tokens': 'फैन टोकन',
    'athletes.back_athlete': '50 टोकन से समर्थन करें',
    'athletes.backed_success': 'एथलीट का समर्थन किया! +50 स्पार्क्स',
    'athletes.funded': 'फंडेड',
    'athletes.target': 'लक्ष्य',
    'athletes.strike_rate': 'स्ट्राइक रेट',
    'athletes.matches': 'मैच',
    'athletes.wickets': 'विकेट',
    'athletes.journey': 'खिलाड़ी का सफर',
    'athletes.fund_purpose': 'अनुदान का उद्देश्य',

    // Deep RL Simulator
    'rl.badge': 'डीप क्यू-लर्निंग और पॉलिसी ग्रेडिएंट आर्किटेक्चर',
    'rl.title': 'डीप रीइन्फोर्समेंट लर्निंग पिच सिम्युलेटर',
    'rl.desc': 'हजारों मैच परिदृश्यों पर प्रशिक्षित मार्कोव निर्णय प्रक्रिया (MDP) नीतियों के साथ कप्तानी निर्णयों का अनुकरण।',
    'rl.train_step': 'RL अनुकूलन चरण चलाएं (+50 युग)',
    'rl.training': 'क्यू-पॉलिसी को अनुकूलित किया जा रहा है...',
    'rl.episodes': 'प्रशिक्षण एपिसोड',
    'rl.reward': 'संचयी इनाम',
    'rl.epsilon': 'अन्वेषण दर (ε)',
    'rl.confidence': 'पॉलिसी आत्मविश्वास',
    'rl.optimal_action': 'इष्टतम अनुशंसित कार्रवाई',
    'rl.batter_type': 'बल्लेबाज प्रोफ़ाइल',
    'rl.bowler_type': 'गेंदबाज प्रोफ़ाइल',
    'rl.phase': 'मैच का चरण',

    // Cyber Security Shield
    'cyber.badge': 'जीरो-ट्रस्ट सुरक्षा और HMAC क्रिप्टोग्राफ़िक मेश',
    'cyber.title': 'साइबर शील्ड और AI प्रॉम्प्ट रक्षा केंद्र',
    'cyber.desc': 'वास्तविक समय के प्रसारण टेलीमेट्री और फैन गवर्नेंस को दुर्भावनापूर्ण हमलों और डेटा छेड़छाड़ से सुरक्षित रखना।',
    'cyber.firewall_title': 'प्रॉम्प्ट इंजेक्शन फ़ायरवॉल',
    'cyber.test_prompt': 'फ़ायरवॉल परीक्षण के लिए प्रश्न दर्ज करें',
    'cyber.inspect_btn': 'जीरो-ट्रस्ट गार्ड से निरीक्षण करें',
    'cyber.tamper_telemetry': 'छेड़छाड़ किए गए डेटा का अनुकरण करें',
    'cyber.restore_telemetry': 'क्रिप्टोग्राफ़िक हस्ताक्षर पुनर्स्थापित करें',
    'cyber.clean': 'स्वच्छ — प्रमाणित',
    'cyber.blocked': 'अवरुद्ध — दुर्भावनापूर्ण खतरा पाया गया',
    'cyber.signature_valid': 'क्रिप्टोग्राफ़िक HMAC हस्ताक्षर सत्यापित',
    'cyber.signature_invalid': 'छेड़छाड़ का पता चला: हस्ताक्षर बेमेल',

    // User Profile
    'profile.title': 'फैन सह-निर्माता सिंक प्रोफ़ाइल',
    'profile.handle': 'लोरकीपर आईडी',
    'profile.sparks_balance': 'फैन स्पार्क्स बैलेंस',
    'profile.credentials': 'सत्यापित आईसीसी क्रेडेंशियल्स',
    'profile.achievements': 'अनलॉक की गई उपलब्धियां',
    'profile.connected': 'सिनेप्स जुड़ा हुआ है',
    'profile.logout': 'फैनवर्स से साइन आउट करें',

    // Authentication Modal
    'auth.title': 'ऑरा लोरकीपर एक्सेस',
    'auth.subtitle': 'क्रिप्टोग्राफ़िक कीपास या ईमेल सत्यापन के साथ साइन इन करें',
    'auth.email_label': 'निर्माता ईमेल या Web3 हैंडल',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'सत्यापन साइफर उत्पन्न करें',
    'auth.otp_title': '6-अंकीय सत्यापन साइफर दर्ज करें',
    'auth.otp_desc': 'आपके हैंडल पर एक एकल-उपयोग क्रिप्टोग्राफ़िक टोकन भेजा गया है।',
    'auth.biometric': 'बायोमेट्रिक पासकी का उपयोग करें',
    'auth.verifying': 'क्रिप्टोग्राफ़िक साइफर का सत्यापन हो रहा है...',
    'auth.success': 'प्रमाणीकरण सफल! फैनवर्स में प्रवेश...',
    'auth.back': 'वापस',
  },

  te: {
    // Nav Tabs
    'nav.discover': 'కనుగొనండి',
    'nav.shorts': 'షార్ట్స్',
    'nav.tactical': 'వ్యూహాత్మక AI',
    'nav.stadium3d': '3D స్టేడియం',
    'nav.analytics': 'రాడార్',
    'nav.rl': 'RL ఏజెంట్',
    'nav.cybersecurity': 'సైబర్ షీల్డ్',
    'nav.athletes': 'క్రీడాకారులు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.login': 'లాగిన్ / రిజిస్టర్',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.sparks': 'స్పార్క్స్',
    'nav.live_mesh': 'ఐసీసీ లైవ్ టోర్నమెంట్ మెష్',
    'nav.over_live': 'ఓవర్ 14.3 లైవ్',

    // 3D Stadium
    'stadium.title': 'హైపర్-రియలిస్టిక్ 3D WebGL క్రికెట్ స్టేడియం',
    'stadium.subtitle': 'వాల్యూమెట్రిక్ లైటింగ్, ప్రొసీజరల్ అల్లికలు & భౌతిక ఇంజిన్',
    'stadium.desc': '4 ఫ్లడ్‌లైట్ వాల్యూమెట్రిక్ కిరణాలు, ప్రొసీజరల్ పచ్చిక, పిచ్ మార్కులు, యానిమేటెడ్ LED హోర్డింగ్‌లు మరియు ఎగిరే బెయిల్స్ భౌతికశాస్త్రం.',
    'stadium.play': 'ప్లే',
    'stadium.pause': 'పాజ్',
    'stadium.reset': 'రీసెట్',
    'stadium.cam_broadcast': 'ప్రసారం',
    'stadium.cam_batter': 'బ్యాటర్ దృశ్యం',
    'stadium.cam_hawkeye': 'హాక్-ఐ',
    'stadium.cam_topdown': 'పైనుండి దృశ్యం',
    'stadium.cam_stump': 'స్టంప్ క్యామ్',
    'stadium.cam_drone': 'డ్రోన్ ఆర్బిట్',
    'stadium.cam_ballfollow': 'బాల్ ట్రాకింగ్',
    'stadium.delivery': 'బౌలింగ్:',
    'stadium.del_seam': '142 కిమీ/గం సీమ్',
    'stadium.del_spin': '86 కిమీ/గం స్పిన్',
    'stadium.del_yorker': '148 కిమీ/గం యార్కర్',
    'stadium.shot': 'షాట్:',
    'stadium.shot_cover': 'కవర్ డ్రైవ్ (6)',
    'stadium.shot_pull': 'పుల్ షాట్ (4)',
    'stadium.shot_straight': 'స్ట్రెయిట్ డ్రైవ్ (4)',
    'stadium.shot_upper': 'అప్పర్ కట్ (6)',
    'stadium.shot_wicket': 'వికెట్ ⚡',
    'stadium.lighting': 'లైటింగ్:',
    'stadium.light_day': 'పగలు',
    'stadium.light_sunset': 'సూర్యాస్తమయం',
    'stadium.light_night': 'రాత్రి',
    'stadium.trail': 'హాక్-ఐ ట్రయల్',
    'stadium.flashes': 'ప్రేక్షకుల ఫ్లాష్‌లు',
    'stadium.in_flight': 'గాల్లో ఉంది',
    'stadium.contact_made': 'తాకింది',
    'stadium.ready': 'సిద్ధం',

    // Tactical AI Co-Pilot
    'tactical.badge': 'AI వ్యూహాత్మక మేధస్సు & బహుళ-మోడల్ ఎన్సెంబల్',
    'tactical.title': 'వ్యూహాత్మక కో-పైలట్ & AI మోడల్ స్టూడియో',
    'tactical.subtitle': '2,896 మ్యాచ్ ఫైళ్లు (7,119 వ్యూహాత్మక స్థితులు) మరియు 90,308 ఆటగాళ్ల రికార్డులతో శిక్షణ పొందింది.',
    'tactical.tab_copilot': 'కో-పైలట్ & రాడార్',
    'tactical.tab_matchup': 'మ్యాచ్‌అప్ మ్యాట్రిక్స్',
    'tactical.tab_inplay': 'ఇన్-ప్లే విన్ సిమ్యులేషన్',
    'tactical.tab_studio': 'AI స్టూడియో & దృశ్యాలు',
    'tactical.field_radar': 'డైనమిక్ ఫీల్డ్ ప్లేస్‌మెంట్ విజువలైజర్',
    'tactical.suggested_questions': 'AI సూచించిన వ్యూహాత్మక ప్రశ్నలు',
    'tactical.click_analyze': 'విశ్లేషించడానికి క్లిక్ చేయండి',
    'tactical.ask_placeholder': 'వ్యూహాత్మక ప్రశ్న అడగండి (ఉదా. కెప్టెన్ డీప్ స్లిప్‌ను ఎందుకు ఉంచారు?)...',
    'tactical.speak_guidance': 'వ్యూహం వినండి',
    'tactical.listen_review': 'ఓవర్ సమీక్ష వినండి',
    'tactical.threat_high': 'అధిక ముప్పు',
    'tactical.threat_vulnerable': 'బలహీనమైనది',
    'tactical.threat_neutral': 'తటస్థం',
    'tactical.threat_favorable': 'అనుకూలం',

    // Data Analytics
    'analytics.badge': 'బిగ్ డేటా క్రికెట్ అనలిటిక్స్ & ఇంటెలిజెన్స్ ప్లాట్‌ఫామ్',
    'analytics.title': 'డేటా విశ్లేషణ, మ్యాచ్ గణాంకాలు & ML టెలిమెట్రీ',
    'analytics.subtitle': '2,896 మ్యాచ్ ఫైళ్లు, 90,308 క్రీడాకారుల రికార్డులు మరియు 16,666 ప్రొఫైళ్ల ఆధారంగా రూపొందించబడింది.',
    'analytics.tab_data': 'డేటా విశ్లేషణ',
    'analytics.tab_ml': 'ML అంచనా',
    'analytics.tab_players': 'టాప్ ప్లేయర్స్ (500)',
    'analytics.tab_matches': 'ఇటీవలి మ్యాచ్‌లు',
    'analytics.tab_charts': 'లైవ్ చార్ట్‌లు',
    'analytics.kpi_matches': 'విశ్లేషించిన మ్యాచ్‌లు',
    'analytics.kpi_states': 'వ్యూహాత్మక స్థితులు',
    'analytics.kpi_players': 'ఆటగాళ్ల రికార్డులు',
    'analytics.kpi_accuracy': 'GB ఖచ్చితత్వం',
    'analytics.kpi_t20_par': 'T20 సగటు స్కోరు',
    'analytics.kpi_odi_par': 'ODI సగటు స్కోరు',
    'analytics.team_power_title': 'అత్యున్నత రేటింగ్ పొందిన అంతర్జాతీయ & ఫ్రాంచైజీ జట్లు',
    'analytics.phase_quantiles_title': 'దశల వారీ స్కోరింగ్ అంచనాలు (కనిష్ట వర్సెస్ గరిష్ట)',
    'analytics.leaderboard_title': 'సమగ్ర ఆటగాళ్ల ప్రభావం (CPI) లీడర్‌బోర్డ్',
    'analytics.predict_win': 'గెలుపు సంభావ్యత',
    'analytics.projected_score': 'అంచనా వేసిన మొదటి ఇన్నింగ్స్ స్కోర్',
    'analytics.search_player': 'ఆటగాడు లేదా దేశం పేరుతో వెతకండి...',

    // General
    'common.live': 'లైవ్',
    'common.all': 'అన్నీ',
    'common.runs': 'పరుగులు',
    'common.wickets': 'వికెట్లు',
    'common.strike_rate': 'స్ట్రైక్ రేట్',
    'common.overs': 'ఓవర్లు',
    // Tournament Ribbon & Brand
    'ribbon.tournament': "ఐసీసీ మహిళల T20 ప్రపంచ కప్ ఫైనల్",
    'ribbon.venue': 'దుబాయ్ అంతర్జాతీయ స్టేడియం',
    'ribbon.fans_synced': '8.4M మంది అభిమానులు లైవ్‌లో ఉన్నారు',
    'ribbon.streams': '12 ప్రాంతీయ AI స్ట్రీమ్‌లు',
    'ribbon.zerotrust': 'జీరో-ట్రస్ట్ రక్షణ: సక్రియం',
    'ribbon.sync_langs': '6 భాషలు సమకాలీకరించబడ్డాయి',
    'brand.tagline': 'మల్టీమోడల్ కానన్ • 3D స్టేడియం • లైవ్ ఫ్యాన్డమ్',

    // Hero Section
    'hero.badge': 'జెనెసిస్ V2.4 కానన్ ప్రోటోకాల్ • దుబాయ్ AI షోకేస్',
    'hero.title_pre': 'కలిసి సృష్టించండి',
    'hero.title_gradient': 'అపరిమిత కానన్',
    'hero.title_post': 'AI & మీ అభిమానుల బృందంతో',
    'hero.desc': 'లైవ్ మహిళల క్రికెట్ డేటా స్వయంప్రతిపత్త నిలువు సూక్ష్మ కథలు, 3D స్టేడియం భౌతికశాస్త్రం మరియు సంభాషణాత్మక వ్యూహాత్మక సహ-పైలట్‌ను శక్తివంతం చేసే దివ్య సహకార ప్రపంచంలోకి అడుగుపెట్టండి.',
    'hero.cta_dashboard': 'లైవ్ డాష్‌బోర్డ్ ప్రారంభించండి',
    'hero.cta_auth': 'సైన్ ఇన్ / లోర్‌కీపర్ యాక్సెస్',

    // Featured Multimodal Storyboards
    'featured.title': 'ప్రత్యేక మల్టీమోడల్ స్టోరీబోర్డులు',
    'featured.subtitle': 'నిజ-సమయంలో రూపొందించబడిన ఆటోమేటెడ్ వీడియో-టు-మాంగా అనుసరణలు',
    'featured.view_all': 'అన్నీ చూడండి (28)',
    'featured.card1_title': "షార్జా మిరాజ్: స్మృతి యొక్క 140కిమీ/గం ఎదురుదాడి",
    'featured.card1_desc': '18వ ఓవర్ బంతి డేటా నుండి పునర్నిర్మించబడింది. స్టేబుల్ డిఫ్యూజన్ XL LoRA మరియు వ్యాఖ్యాన సంశ్లేషణతో షోనెన్ మాంగా శైలి.',
    'featured.card1_watch': 'కథ చూడండి',
    'featured.card2_title': "హర్మన్‌ప్రీత్ లెగ్-సైడ్ ట్రాప్: సంభావ్యత విశ్లేషణ",
    'featured.card2_desc': 'సోఫీ ఎక్లెస్టోన్‌కు వ్యతిరేకంగా బ్యాక్‌వర్డ్ స్క్వేర్ లెగ్ మరియు డీప్ మిడ్-వికెట్ ఫీల్డింగ్‌ను వివరించే డీప్ Q-లెర్నింగ్ విశ్లేషణ.',
    'featured.card2_inspect': 'రీప్లే పరిశీలించండి',
    'featured.card3_title': "ఖాట్మండు నుండి లార్డ్స్ వరకు: పూజా మహతో 5-వికెట్ల ఒడిస్సీ",
    'featured.card3_desc': 'నేపాల్ U-19 ఫాస్ట్ బౌలర్‌ను గౌరవించే కమ్యూనిటీ-నిధుల కథ.',
    'featured.card3_tip': 'క్రీడాకారిణికి మద్దతు ఇవ్వండి',

    // Live Co-Creation Arenas
    'arenas.title': 'లైవ్ సహ-సృష్టి రంగాలు',
    'arenas.subtitle': 'మ్యాచ్ కథనాలను సంశ్లేషణ చేసే రియల్-టైమ్ మల్టీప్లేయర్ గదులు',
    'arenas.active_badge': '3 రంగాలు సక్రియంగా ఉన్నాయి',
    'arenas.room1_title': 'సైబర్-వాల్కిరీ రచయితలు',
    'arenas.room1_sub': 'మ్యాచ్: IND-W vs AUS-W (ఫైనల్స్)',
    'arenas.room1_creators': '84 మంది సృష్టికర్తలు',
    'arenas.room1_scene': "ప్రస్తుత దృశ్యం: 19వ ఓవర్లో హర్మన్‌ప్రీత్ రివర్స్-స్వీప్",
    'arenas.room2_title': 'వ్యూహాత్మక విశ్లేషణ గిల్డ్',
    'arenas.room2_sub': 'ఫీల్డ్ జ్యామితి & స్పిన్ పథాలు',
    'arenas.room2_creators': '126 మంది సృష్టికర్తలు',
    'arenas.room2_scene': 'ప్రస్తుత దృశ్యం: 62కిమీ/గం లెగ్ బ్రేక్‌పై PINN ఏరోడైనమిక్ డ్రిఫ్ట్',
    'arenas.room3_title': 'గ్రాస్‌రూట్స్ స్పాట్‌లైట్ స్టూడియో',
    'arenas.room3_sub': 'నేపాల్, థాయిలాండ్ & స్కాట్లాండ్ తారలు',
    'arenas.room3_creators': '62 మంది సృష్టికర్తలు',
    'arenas.room3_scene': 'ప్రస్తుత దృశ్యం: క్రౌడ్‌సోర్స్ గ్రాంట్ మైలురాయి 5,000 స్పార్క్స్',
    'arenas.join_btn': 'సెషన్‌లో చేరండి',

    // Canon Governance Poll
    'poll.badge': 'కానన్ పాలనా ప్రతిపాదన #88',
    'poll.closes': 'ముగియడానికి సమయం 04:18:22',
    'poll.title': 'వ్యూహాత్మక సందిగ్ధత: కెప్టెన్ హర్మన్‌ప్రీత్ ఓవర్ 19.4లో ఏ బంతి వేయాలి?',
    'poll.desc': 'గెలిచిన ఎంపిక రూపొందించబడే క్లైమాక్స్‌ను నిర్ణయిస్తుంది మరియు ఓటర్లకు డబుల్ స్పార్క్స్ అన్‌లాక్ చేస్తుంది.',
    'poll.opt1': 'క్వాంటం గూగ్లీ ట్రాప్‌ను అమలు చేయండి',
    'poll.opt2': 'ఆఫ్-స్టంప్ వెలుపల ప్రామాణిక గుడ్ లెంగ్త్‌ను కొనసాగించండి',
    'poll.opt3': 'స్లాగ్ స్వీప్ కోసం బౌండరీ స్వీపర్‌ను రక్షించండి',
    'poll.total_votes': 'మొత్తం కమ్యూనిటీ ఓట్లు: 3,489',
    'poll.sparks_reward': 'ఓటు వేసినందుకు +50 స్పార్క్స్',

    // Multilingual AI Commentary Player
    'audio.badge': 'బహుభాషా AI వ్యాఖ్యాన సింథసిస్',
    'audio.dialects': '12 మాండలికాలు సిద్ధం',
    'audio.title': 'తెలుగు & తమిళ వాయిస్ సింథసిస్: "షార్జాను కదిలించిన ఆ సిక్సర్"',
    'audio.desc': 'గెలుపు సంభావ్యత మార్పుల ఆధారంగా తీవ్రత మరియు పిచ్‌ను డైనమిక్‌గా స్వీకరించే న్యూరల్ వాయిస్‌ని వినండి.',
    'audio.preview': 'న్యూరల్ వాయిస్ వినండి',
    'audio.pause': 'స్ట్రీమ్ ఆపండి',
    'audio.latency': 'లేటెన్సీ: 280ms',

    // Pillars of Creation
    'pillars.tag': 'సృష్టి యొక్క స్తంభాలు',
    'pillars.title': 'మల్టీ-థ్రెడెడ్ AI ఆర్కిటెక్చర్',
    'pillars.p1_title': 'మల్టీమోడల్ స్టోరీ ఇంజిన్',
    'pillars.p1_desc': 'వచనం, వాయిస్ వ్యాఖ్యానం, నిలువు వీడియో రీఫ్రేమింగ్ మరియు లైవ్ HUD టెలిమెట్రీ 45 సెకన్లలోపు సిద్ధం.',
    'pillars.p2_title': 'సహకార వ్యూహాత్మక కో-పైలట్',
    'pillars.p2_desc': 'సంభాషణాత్మక AI, డైనమిక్ 2D ఫీల్డ్ రాడార్ మరియు 3D WebGL భౌతికశాస్త్రంతో కెప్టెన్సీ ఫీల్డింగ్‌ను వివరిస్తుంది.',
    'pillars.p3_title': 'గ్రాస్‌రూట్స్ ఫ్యూచర్ స్టార్స్ ఫండ్',
    'pillars.p3_desc': 'అభిమానులు మహిళా అథ్లెట్లకు మైక్రో-టోకెన్లను అంకితం చేస్తారు, ఇందులో 15% అసోసియేట్ దేశాల అకాడమీల కోసం కేటాయించబడింది.',

    // Relic Codex
    'codex.tag': 'ఆర్కైవ్స్ & అవశేషాలు',
    'codex.title': 'కానానికల్ క్రీడా కళాఖండాలు & కాలక్రమ రేఖలు',
    'codex.total': 'మొత్తం కళాఖండాలు: 1,420',
    'codex.card1_title': 'వాట్-ఇఫ్ బ్రాంచ్ #44',
    'codex.card1_desc': 'సోఫీ డివైన్ లెగ్-స్పిన్‌తో బౌలింగ్ ప్రారంభించిన ప్రత్యామ్నాయ చరిత్ర.',
    'codex.card2_title': 'హాక్-ఐ స్పిన్ అవశేషం',
    'codex.card2_desc': 'ICC టెలిమెట్రిక్ ఫీడ్ ద్వారా సంతకం చేయబడిన 3D గణిత పథం టోకెన్.',
    'codex.card3_title': 'క్లచ్ ఓవర్ మాస్టర్',
    'codex.card3_desc': '19వ ఓవర్ యార్కర్‌ను సరిగ్గా అంచనా వేసినందుకు అభిమానులకు ఇచ్చే బ్యాడ్జ్.',
    'codex.card4_title': 'క్వాంటం ఫిజిక్స్ నోడ్',
    'codex.card4_desc': 'ఏదైనా చారిత్రక డెలివరీపై భౌతికశాస్త్ర-ఆధారిత న్యూరల్ నెట్‌వర్క్ పరీక్షలను అమలు చేయండి.',

    // Community Stats
    'community.creators': 'ప్రపంచవ్యాప్తంగా 140,000+ సహ-సృష్టికర్తలు',
    'community.active_desc': '850+ మహిళా క్రికెట్ టోర్నమెంట్లు & కథనాలలో చురుకుగా ఉన్నారు',
    'community.verified': 'ధృవీకరించబడిన ICC కానన్ లెడ్జర్ #8802',
    'community.enter': 'ఇప్పుడే ప్రవేశించండి',

    // Shorts & Vertical Reels
    'shorts.badge': 'స్వయంప్రతిపత్త మల్టీమోడల్ ముఖ్యాంశాల పైప్‌లైన్',
    'shorts.title': 'నిలువు సూక్ష్మ-కథలు & బహుభాషా వాయిస్ సంశ్లేషణ',
    'shorts.desc': '45 సెకన్లలోపు ముడి ICC ప్రసార వీడియోను 9:16 నిలువు రీల్స్‌గా మార్చండి, ఇందులో ఆటోమేటెడ్ బంతి డేటా మరియు 12+ భాషలలో వ్యాఖ్యానం ఉంటాయి.',
    'shorts.edge_ingestion': 'ఎడ్జ్ ఇంగెషన్: 38s',
    'shorts.tab_shorts': '9:16 షార్ట్స్',
    'shorts.tab_long': '16:9 ప్రసారం',
    'shorts.exit_velocity': 'ఎగ్జిట్ వేగం',
    'shorts.launch_angle': 'లాంచ్ కోణం',
    'shorts.distance': 'దూరం',
    'shorts.win_prob_delta': 'గెలుపు సంభావ్యత మార్పు',
    'shorts.tactical_breakdown': 'వ్యూహాత్మక విశ్లేషణ',
    'shorts.ai_commentary': 'AI న్యూరల్ వ్యాఖ్యానం',
    'shorts.play_audio': 'వాయిస్‌లో వినండి',
    'shorts.stop_audio': 'వాయిస్ ఆపండి',
    'shorts.share': 'రీల్ షేర్ చేయండి',
    'shorts.all': 'అన్నీ',
    'shorts.cat_masterclass': 'మాస్టర్‌క్లాస్',
    'shorts.cat_pace': 'పేస్ ఎటాక్',
    'shorts.cat_clutch': 'క్లచ్ డిఫెన్స్',
    'shorts.cat_captaincy': 'కెప్టెన్సీ',
    'shorts.cat_fielding': 'ఫీల్డింగ్',
    'shorts.cat_spin': 'స్పిన్ మ్యాజిక్',
    'shorts.cat_power': 'పవర్ హిట్టింగ్',
    'shorts.cat_death': 'డెత్ ఓవర్ల బౌలింగ్',
    'shorts.cat_grassroots': 'గ్రాస్‌రూట్స్ ప్రతిభ',
    'shorts.cat_wicketkeeping': 'వికెట్‌కీపింగ్',
    'shorts.cat_final': 'తుది క్షణాలు',

    // Athlete Digital Passport
    'athletes.badge': 'సాధికారత & అట్టడుగు వర్గాల సమగ్రత',
    'athletes.title': 'అథ్లెట్ డిజిటల్ పాస్‌పోర్ట్ & మైక్రో-స్పాన్సర్‌షిప్ హబ్',
    'athletes.desc': 'క్రీడాకారులకు నిధుల కొరతను తొలగించడం. అభిమానులు నేరుగా మహిళా అథ్లెట్లకు మద్దతు ఇస్తారు, కిట్లు మరియు ప్రయాణానికి నిధులు సమకూరుస్తారు.',
    'athletes.balance': 'మీ ఫ్యాన్ బ్యాలెన్స్',
    'athletes.tokens': 'ఫ్యాన్ టోకెన్లు',
    'athletes.back_athlete': '50 టోకెన్లతో మద్దతు ఇవ్వండి',
    'athletes.backed_success': 'అథ్లెట్‌కు మద్దతు ఇచ్చారు! +50 స్పార్క్స్',
    'athletes.funded': 'సమకూరిన నిధులు',
    'athletes.target': 'లక్ష్యం',
    'athletes.strike_rate': 'స్ట్రైక్ రేట్',
    'athletes.matches': 'మ్యాచ్‌లు',
    'athletes.wickets': 'వికెట్లు',
    'athletes.journey': 'క్రీడాకారిణి ప్రయాణం',
    'athletes.fund_purpose': 'గ్రాంట్ ప్రయోజనం',

    // Deep RL Simulator
    'rl.badge': 'డీప్ Q-లెర్నింగ్ & పాలసీ గ్రేడియంట్ ఆర్కిటెక్చర్',
    'rl.title': 'డీప్ రీఇన్‌ఫోర్స్‌మెంట్ లెర్నింగ్ పిచ్ సిమ్యులేటర్',
    'rl.desc': 'వేలాది మ్యాచ్ దృశ్యాలపై శిక్షణ పొందిన మార్కోవ్ నిర్ణయ ప్రక్రియ (MDP) విధానాలతో కెప్టెన్సీ నిర్ణయాల అనుకరణ.',
    'rl.train_step': 'RL ఆప్టిమైజేషన్ దశను అమలు చేయండి (+50 యుగాలు)',
    'rl.training': 'Q-విధానాన్ని ఆప్టిమైజ్ చేస్తోంది...',
    'rl.episodes': 'శిక్షణ ఎపిసోడ్‌లు',
    'rl.reward': 'సంచిత బహుమతి',
    'rl.epsilon': 'అన్వేషణ రేటు (ε)',
    'rl.confidence': 'విధాన విశ్వాసం',
    'rl.optimal_action': 'సిఫార్సు చేయబడిన సరైన చర్య',
    'rl.batter_type': 'బ్యాటర్ ప్రొఫైల్',
    'rl.bowler_type': 'బౌలర్ ప్రొఫైల్',
    'rl.phase': 'మ్యాచ్ దశ',

    // Cyber Security Shield
    'cyber.badge': 'జీరో-ట్రస్ట్ భద్రత & HMAC క్రిప్టోగ్రాఫిక్ మెష్',
    'cyber.title': 'సైబర్ షీల్డ్ & AI ప్రాంప్ట్ రక్షణ కేంద్రం',
    'cyber.desc': 'నిజ-సమయ ప్రసార డేటాను హానికరమైన దాడులు మరియు డేటా ట్యాంపరింగ్ నుండి రక్షించడం.',
    'cyber.firewall_title': 'ప్రాంప్ట్ ఇంజెక్షన్ ఫైర్‌వాల్',
    'cyber.test_prompt': 'ఫైర్‌వాల్ పరీక్ష కోసం ప్రశ్నను నమోదు చేయండి',
    'cyber.inspect_btn': 'జీరో-ట్రస్ట్ గార్డ్‌తో పరిశీలించండి',
    'cyber.tamper_telemetry': 'ట్యాంపర్డ్ డేటాను అనుకరించండి',
    'cyber.restore_telemetry': 'క్రిప్టోగ్రాఫిక్ సంతకాన్ని పునరుద్ధరించండి',
    'cyber.clean': 'క్లీన్ — ప్రామాణీకరించబడింది',
    'cyber.blocked': 'బ్లాక్ చేయబడింది — హానికరమైన ముప్పు గుర్తించబడింది',
    'cyber.signature_valid': 'క్రిప్టోగ్రాఫిక్ HMAC సంతకం ధృవీకరించబడింది',
    'cyber.signature_invalid': 'ట్యాంపరింగ్ గుర్తించబడింది: సంతకం సరిపోలడం లేదు',

    // User Profile
    'profile.title': 'ఫ్యాన్ సహ-సృష్టికర్త సినాప్స్ ప్రొఫైల్',
    'profile.handle': 'లోర్‌కీపర్ ID',
    'profile.sparks_balance': 'ఫ్యాన్ స్పార్క్స్ నిల్వ',
    'profile.credentials': 'ధృవీకరించబడిన ICC ఆధారాలు',
    'profile.achievements': 'అన్‌లాక్ చేయబడిన విజయాలు',
    'profile.connected': 'సినాప్స్ కనెక్ట్ చేయబడింది',
    'profile.logout': 'ఫ్యాన్‌వర్స్ నుండి నిష్క్రమించండి',

    // Authentication Modal
    'auth.title': 'ఆరా లోర్‌కీపర్ యాక్సెస్',
    'auth.subtitle': 'క్రిప్టోగ్రాఫిక్ కీపాస్ లేదా ఇమెయిల్ ధృవీకరణతో సైన్ ఇన్ చేయండి',
    'auth.email_label': 'సృష్టికర్త ఇమెయిల్ లేదా Web3 హ్యాండిల్',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'ధృవీకరణ సైఫర్‌ను రూపొందించండి',
    'auth.otp_title': '6-అంకెల ధృవీకరణ సైఫర్‌ను నమోదు చేయండి',
    'auth.otp_desc': 'మీ హ్యాండిల్‌కు ఒక-సారి ఉపయోగించే క్రిప్టోగ్రాఫిక్ టోకెన్ పంపబడింది.',
    'auth.biometric': 'బయోమెట్రిక్ పాస్‌కీని ఉపయోగించండి',
    'auth.verifying': 'క్రిప్టోగ్రాఫిక్ సైఫర్ ధృవీకరించబడుతోంది...',
    'auth.success': 'ప్రామాణీకరణ విజయవంతమైంది! ఫ్యాన్‌వర్స్‌లోకి ప్రవేశిస్తోంది...',
    'auth.back': 'వెనుకకు',
  },

  ta: {
    // Nav Tabs
    'nav.discover': 'கண்டறிக',
    'nav.shorts': 'குறும்படங்கள்',
    'nav.tactical': 'தந்திரோபாய AI',
    'nav.stadium3d': '3D அரங்கம்',
    'nav.analytics': 'ரேடார்',
    'nav.rl': 'RL முகவர்',
    'nav.cybersecurity': 'சைபர் பாதுகாப்பு',
    'nav.athletes': 'வீரர்கள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.login': 'உள்நுழைய / பதிவு',
    'nav.logout': 'வெளியேறு',
    'nav.sparks': 'ஸ்பார்க்ஸ்',
    'nav.live_mesh': 'ஐசிசி நேரலை போட்டி மெஷ்',
    'nav.over_live': 'ஓவர் 14.3 நேரலை',

    // 3D Stadium
    'stadium.title': 'இயற்கையான 3D WebGL கிரிக்கெட் அரங்கம்',
    'stadium.subtitle': 'ஒளிரும் விளக்குகள், புல்வெளி மற்றும் இயற்பியல் இயந்திரம்',
    'stadium.desc': '4 ஃப்ளட்லைட்கள், பச்சை புல்வெளி தடம், களிமண் பிட்ச், ஒளிரும் எல்இடி பலகைகள் மற்றும் பறக்கும் பெயில்கள்.',
    'stadium.play': 'இயக்கு',
    'stadium.pause': 'நிறுத்து',
    'stadium.reset': 'மீட்டமை',
    'stadium.cam_broadcast': 'ஒளிபரப்பு',
    'stadium.cam_batter': 'பேட்டர் பார்வை',
    'stadium.cam_hawkeye': 'ஹாக்-ஐ',
    'stadium.cam_topdown': 'மேல் பார்வை',
    'stadium.cam_stump': 'ஸ்டம்ப் கேமரா',
    'stadium.cam_drone': 'ட்ரோன் சுழற்சி',
    'stadium.cam_ballfollow': 'பந்து பின்தொடர்',
    'stadium.delivery': 'பந்துவீச்சு:',
    'stadium.del_seam': '142 கிமீ/ம சீம்',
    'stadium.del_spin': '86 கிமீ/ம ஸ்பின்',
    'stadium.del_yorker': '148 கிமீ/ம யார்க்கர்',
    'stadium.shot': 'ஷாட்:',
    'stadium.shot_cover': 'கவர் டிரைவ் (6)',
    'stadium.shot_pull': 'புல் ஷாட் (4)',
    'stadium.shot_straight': 'ஸ்ட்ரெய்ட் டிரைவ் (4)',
    'stadium.shot_upper': 'அப்பர் கட் (6)',
    'stadium.shot_wicket': 'விக்கெட் ⚡',
    'stadium.lighting': 'விளக்குகள்:',
    'stadium.light_day': 'பகல்',
    'stadium.light_sunset': 'மாலைப்பொழுது',
    'stadium.light_night': 'இரவு',
    'stadium.trail': 'ஹாக்-ஐ பாதை',
    'stadium.flashes': 'ரசிகர் கேமரா ஒளி',
    'stadium.in_flight': 'காற்றில்',
    'stadium.contact_made': 'தாக்கம் ஏற்பட்டது',
    'stadium.ready': 'தயார்',

    // Tactical AI Co-Pilot
    'tactical.badge': 'AI தந்திரோபாய நுண்ணறிவு & மாடல் குழுமம்',
    'tactical.title': 'தந்திரோபாய இணை-பைலட் & AI ஸ்டுடியோ',
    'tactical.subtitle': '2,896 போட்டிகள் மற்றும் 90,308 வீரர்களின் தரவுகளில் பயிற்சியளிக்கப்பட்டது.',
    'tactical.tab_copilot': 'இணை-பைலட் & ரேடார்',
    'tactical.tab_matchup': 'மோதல் மேட்ரிக்ஸ்',
    'tactical.tab_inplay': 'நேரலை வெற்றி உருவகப்படுத்துதல்',
    'tactical.tab_studio': 'AI ஸ்டுடியோ & காட்சிகள்',
    'tactical.field_radar': 'கள அமைப்பு காட்சிப்படுத்தி',
    'tactical.suggested_questions': 'AI பரிந்துரைக்கும் கேள்விகள்',
    'tactical.click_analyze': 'பகுப்பாய்வு செய்ய கிளிக் செய்க',
    'tactical.ask_placeholder': 'தந்திரோபாய கேள்வி கேட்கவும்...',
    'tactical.speak_guidance': 'வழிகாட்டலைக் கேட்கவும்',
    'tactical.listen_review': 'ஓவர் மதிப்பாய்வு கேட்கவும்',
    'tactical.threat_high': 'அதிக அச்சுறுத்தல்',
    'tactical.threat_vulnerable': 'பாதிக்கப்படக்கூடியது',
    'tactical.threat_neutral': 'நடுநிலை',
    'tactical.threat_favorable': 'சாதகமானது',

    // Data Analytics
    'analytics.badge': 'பிக் டேட்டா கிரிக்கெட் அனலிட்டிக்ஸ் தளம்',
    'analytics.title': 'தரவு பகுப்பாய்வு, போட்டி புள்ளிவிவரங்கள் & ML',
    'analytics.subtitle': '2,896 போட்டிகள் மற்றும் 90,308 வீரர்களின் தரவுத்தளத்தில் இருந்து பெறப்பட்டது.',
    'analytics.tab_data': 'தரவு பகுப்பாய்வு',
    'analytics.tab_ml': 'ML கணிப்பாளர்',
    'analytics.tab_players': 'சிறந்த வீரர்கள் (500)',
    'analytics.tab_matches': 'சமீபத்திய போட்டிகள்',
    'analytics.tab_charts': 'நேரலை வரைபடங்கள்',
    'analytics.kpi_matches': 'பகுப்பாய்வு செய்யப்பட்ட போட்டிகள்',
    'analytics.kpi_states': 'தந்திரோபாய நிலைகள்',
    'analytics.kpi_players': 'வீரர் பதிவுகள்',
    'analytics.kpi_accuracy': 'GB துல்லியம்',
    'analytics.kpi_t20_par': 'T20 சராசரி ஸ்கோர்',
    'analytics.kpi_odi_par': 'ODI சராசரி ஸ்கோர்',
    'analytics.team_power_title': 'அதிக மதிப்பீடு பெற்ற அணிகள்',
    'analytics.phase_quantiles_title': 'கட்ட வாரியான ரன் எதிர்பார்ப்புகள்',
    'analytics.leaderboard_title': 'வீரர் தாக்க (CPI) தரவரிசை',
    'analytics.predict_win': 'வெற்றி வாய்ப்பு',
    'analytics.projected_score': 'கணிக்கப்பட்ட முதல் இன்னிங்ஸ் ஸ்கோர்',
    'analytics.search_player': 'வீரர் அல்லது நாடு மூலம் தேடுக...',

    // General
    'common.live': 'நேரலை',
    'common.all': 'அனைத்தும்',
    'common.runs': 'ரன்கள்',
    'common.wickets': 'விக்கெட்டுகள்',
    'common.strike_rate': 'ஸ்ட்ரைக் ரேட்',
    // Tournament Ribbon & Brand
    'ribbon.tournament': 'ஐசிசி மகளிர் டி20 உலகக் கோப்பை இறுதிப் போட்டி',
    'ribbon.venue': 'துபாய் சர்வதேச அரங்கம்',
    'ribbon.fans_synced': '8.4M ரசிகர்கள் நேரலையில் இணைந்தனர்',
    'ribbon.streams': '12 பிராந்திய AI ஸ்ட்ரீம்கள்',
    'ribbon.zerotrust': 'ஜீரோ-டிரஸ்ட் பாதுகாப்பு: இயங்குகிறது',
    'ribbon.sync_langs': '6 மொழிகள் ஒருங்கிணைக்கப்பட்டுள்ளன',
    'brand.tagline': 'மல்டிமாடல் கேனான் • 3D அரங்கம் • நேரலை ரசிகர்கள்',

    // Hero Section
    'hero.badge': 'ஜெனிசிஸ் V2.4 கேனான் நெறிமுறை • துபாய் AI கண்காட்சி',
    'hero.title_pre': 'இணைந்து உருவாக்குங்கள்',
    'hero.title_gradient': 'எல்லையற்ற கேனான்',
    'hero.title_post': 'AI மற்றும் உங்கள் ரசிகர் மன்றத்துடன்',
    'hero.desc': 'நேரலை மகளிர் கிரிக்கெட் தரவு தானியங்கி மைக்ரோ கதைகள், 3D அரங்கு இயற்பியல் மற்றும் உத்திசார் AI ஆகியவற்றை இயக்கும் கூட்டு உலகத்தில் நுழையுங்கள்.',
    'hero.cta_dashboard': 'நேரலை டாஷ்போர்டைத் தொடங்குக',
    'hero.cta_auth': 'உள்நுழைக / லோர்கீப்பர் அணுகல்',

    // Featured Multimodal Storyboards
    'featured.title': 'சிறப்பு மல்டிமாடல் ஸ்டோரிபோர்டுகள்',
    'featured.subtitle': 'நிகழ்நேரத்தில் உருவாக்கப்பட்ட தானியங்கி வீடியோ-டு-மங்கா வடிவங்கள்',
    'featured.view_all': 'அனைத்தையும் காண்க (28)',
    'featured.card1_title': 'ஷார்ஜா அதிசயம்: ஸ்மிருதியின் 140 கிமீ/மணி எதிர்த்தாக்குதல்',
    'featured.card1_desc': '18வது ஓவர் பந்து தரவுகளிலிருந்து மீளுருவாக்கம் செய்யப்பட்டது. ஸ்டேபிள் டிஃப்யூஷன் XL LoRA உடன் ஷோனன் மங்கா அழகியல்.',
    'featured.card1_watch': 'கதையைப் பார்க்கவும்',
    'featured.card2_title': 'ஹர்மன்பிரீத்தின் லெக்-சைட் பொறி: நிகழ்தகவு பகுப்பாய்வு',
    'featured.card2_desc': 'சோஃபி எக்லெஸ்டோனுக்கு எதிரான ஃபீல்டிங் அமைப்பை விளக்கும் டீப் Q-லேர்னிங் பகுப்பாய்வு.',
    'featured.card2_inspect': 'ரீப்ளே ஆராய்க',
    'featured.card3_title': 'காத்மாண்டு முதல் லார்ட்ஸ் வரை: பூஜா மஹதோவின் 5-விக்கெட் பயணம்',
    'featured.card3_desc': 'நேபாளத்தின் U-19 வேகப்பந்து வீச்சாளரை கௌரவிக்கும் சமூக நிதி உதவி கதை.',
    'featured.card3_tip': 'வீராங்கனைக்கு வெகுமதி அளிக்க',

    // Live Co-Creation Arenas
    'arenas.title': 'நேரலை இணை-உருவாக்க அரங்கங்கள்',
    'arenas.subtitle': 'போட்டி கதைகளை ஒருங்கிணைக்கும் நிகழ்நேர மல்டிபிளேயர் அறைகள்',
    'arenas.active_badge': '3 அரங்கங்கள் செயலில் உள்ளன',
    'arenas.room1_title': 'சைபர்-வால்கெய்ரி எழுத்தாளர்கள்',
    'arenas.room1_sub': 'போட்டி: IND-W vs AUS-W (இறுதிப் போட்டி)',
    'arenas.room1_creators': '84 படைப்பாளர்கள்',
    'arenas.room1_scene': 'தற்போதைய காட்சி: 19வது ஓவரில் ஹர்மன்பிரீத்தின் ரிவர்ஸ்-ஸ்வீப்',
    'arenas.room2_title': 'உத்திசார் பகுப்பாய்வு சங்கம்',
    'arenas.room2_sub': 'கள வடிவவியல் & சுழற்பந்து பாதைகள்',
    'arenas.room2_creators': '126 படைப்பாளர்கள்',
    'arenas.room2_scene': 'தற்போதைய காட்சி: 62 கிமீ/மணி லெக் பிரேக்கில் ஏரோடைனமிக் ட்ரிஃப்ட்',
    'arenas.room3_title': 'அடிமட்ட திறமை அரங்கம்',
    'arenas.room3_sub': 'நேபாளம், தாய்லாந்து & ஸ்காட்லாந்து நட்சத்திரங்கள்',
    'arenas.room3_creators': '62 படைப்பாளர்கள்',
    'arenas.room3_scene': 'தற்போதைய காட்சி: சமூக நிதி மைல்கல் 5,000 ஸ்பார்க்ஸ்',
    'arenas.join_btn': 'அமர்வில் இணையவும்',

    // Canon Governance Poll
    'poll.badge': 'கேனான் ஆளுகை முன்மொழிவு #88',
    'poll.closes': 'முடிவடைய இன்னும் 04:18:22 உள்ளது',
    'poll.title': 'உத்திசார் குழப்பம்: கேப்டன் ஹர்மன்பிரீத் 19.4 ஓவரில் என்ன பந்து வீச வேண்டும்?',
    'poll.desc': 'வெற்றி பெறும் விருப்பம் உருவாகும் உச்சக்கட்ட காட்சியை தீர்மானிக்கும் மற்றும் இரட்டிப்பு ஸ்பார்க்ஸ்களை வழங்கும்.',
    'poll.opt1': 'குவாண்டம் கூக்ளி பொறி அமைத்தல்',
    'poll.opt2': 'ஆஃப்-ஸ்டம்பிற்கு வெளியே குட் லென்த்தில் வீசுதல்',
    'poll.opt3': 'ஸ்லாக் ஸ்வீப்பைத் தடுக்க எல்லைக் கோட்டு ஃபீல்டரைக் கொண்டு வருதல்',
    'poll.total_votes': 'மொத்த சமூக வாக்குகள்: 3,489',
    'poll.sparks_reward': 'வாக்களித்தவுடன் +50 ஸ்பார்க்ஸ்',

    // Multilingual AI Commentary Player
    'audio.badge': 'பன்மொழி AI வர்ணனை தொகுப்பு',
    'audio.dialects': '12 வட்டார மொழிகள் தயார்',
    'audio.title': 'வங்காளம் & தமிழ் குரல் தொகுப்பு: "ஷார்ஜாவை அதிரவைத்த அந்த சிக்ஸர்"',
    'audio.desc': 'வெற்றி வாய்ப்பு மாற்றங்களுக்கு ஏற்ப குரலின் தீவிரம் மற்றும் ஒலியளவை மாற்றியமைக்கும் நியூரல் குரல் பதிவை கேளுங்கள்.',
    'audio.preview': 'குரல் முன்னோட்டம்',
    'audio.pause': 'நிறுத்துக',
    'audio.latency': 'தாமதம்: 280ms',

    // Pillars of Creation
    'pillars.tag': 'படைப்பின் தூண்கள்',
    'pillars.title': 'மல்டி-த்ரெட்டட் AI கட்டமைப்பு',
    'pillars.p1_title': 'மல்டிமாடல் கதை இயந்திரம்',
    'pillars.p1_desc': 'உரை, குரல் வர்ணனை, செங்குத்து வீடியோ மற்றும் நேரலை HUD ஆகியவை 45 வினாடிகளில் தொகுக்கப்படுகின்றன.',
    'pillars.p2_title': 'கூட்டு உத்திசார் துணை-பைலட்',
    'pillars.p2_desc': 'உரையாடல் AI, டைனமிக் 2D ரேடார் மற்றும் 3D WebGL மூலம் கேப்டன்சி ஃபீல்டிங்கை எளிதாக்குகிறது.',
    'pillars.p3_title': 'அடிமட்ட எதிர்கால நட்சத்திரங்கள் நிதி',
    'pillars.p3_desc': 'ரசிகர்கள் வீராங்கனைகளுக்கு டோக்கன்களை வழங்குகிறார்கள், இதில் 15% அகாடமிகளுக்கு ஒதுக்கப்படுகிறது.',

    // Relic Codex
    'codex.tag': 'காப்பகங்கள் & நினைவு முனையங்கள்',
    'codex.title': 'அங்கீகரிக்கப்பட்ட விளையாட்டு நினைவுப் பொருட்கள்',
    'codex.total': 'மொத்த பொருட்கள்: 1,420',
    'codex.card1_title': 'மாற்று வரலாறு கிளை #44',
    'codex.card1_desc': 'சோஃபி டிவைன் லெக்-ஸ்பின் மூலம் பந்துவீச்சைத் தொடங்கிய மாற்று வரலாறு.',
    'codex.card2_title': 'ஹாக்-ஐ ஸ்பின் நினைவுப்பொருள்',
    'codex.card2_desc': 'ஐசிசி டெலிமெட்ரிக் ஊட்டம் மூலம் கையொப்பமிடப்பட்ட 3D கணித பாதை டோக்கன்.',
    'codex.card3_title': 'கிளட்ச் ஓவர் மாஸ்டர்',
    'codex.card3_desc': '19வது ஓவர் யார்க்கரை சரியாக கணித்த ரசிகர்களுக்கு வழங்கப்படும் பேட்ஜ்.',
    'codex.card4_title': 'குவாண்டம் இயற்பியல் முனையம்',
    'codex.card4_desc': 'எந்தவொரு வரலாற்று பந்திலும் இயற்பியல் சார்ந்த நியூரல் நெட்வொர்க் சோதனைகளை இயக்கவும்.',

    // Community Stats
    'community.creators': 'உலகளவில் 140,000+ இணை படைப்பாளர்கள்',
    'community.active_desc': '850+ மகளிர் கிரிக்கெட் போட்டிகள் மற்றும் கதை சுழற்சிகளில் செயலில் உள்ளனர்',
    'community.verified': 'சரிபார்க்கப்பட்ட ICC கேனான் லெட்ஜர் #8802',
    'community.enter': 'இப்போதே நுழையுங்கள்',

    // Shorts & Vertical Reels
    'shorts.badge': 'சுயாட்சி மல்டிமாடல் ஹைலைட் பைப்லைன்',
    'shorts.title': 'செங்குத்து மைக்ரோ-கதைகள் & பலமொழி குரல் தொகுப்பு',
    'shorts.desc': 'நேரலை ஐசிசி ஒளிபரப்பு வீடியோவை 45 வினாடிகளுக்குள் 9:16 செங்குத்து ரீல்களாக மாற்றவும், தானியங்கி பந்து தரவு மற்றும் 12+ மொழிகளில் வர்ணனையுடன்.',
    'shorts.edge_ingestion': 'எட்ஜ் உட்கொள்ளல்: 38s',
    'shorts.tab_shorts': '9:16 குறும்படங்கள்',
    'shorts.tab_long': '16:9 ஒளிபரப்பு',
    'shorts.exit_velocity': 'வெளியேறும் வேகம்',
    'shorts.launch_angle': 'ஏவுதல் கோணம்',
    'shorts.distance': 'தூரம்',
    'shorts.win_prob_delta': 'வெற்றி வாய்ப்பு மாற்றம்',
    'shorts.tactical_breakdown': 'தந்திரோபாய முறிவு',
    'shorts.ai_commentary': 'AI நியூரல் வர்ணனை',
    'shorts.play_audio': 'குரலில் கேட்கவும்',
    'shorts.stop_audio': 'குரலை நிறுத்தவும்',
    'shorts.share': 'ரீலைப் பகிரவும்',
    'shorts.all': 'அனைத்தும்',
    'shorts.cat_masterclass': 'மாஸ்டர்கிளாஸ்',
    'shorts.cat_pace': 'வேகப்பந்து தாக்குதல்',
    'shorts.cat_clutch': 'நெருக்கடி தற்காப்பு',
    'shorts.cat_captaincy': 'கேப்டன்சி',
    'shorts.cat_fielding': 'பீல்டிங்',
    'shorts.cat_spin': 'சுழற்பந்து மந்திரம்',
    'shorts.cat_power': 'சக்திவாய்ந்த பேட்டிங்',
    'shorts.cat_death': 'கடைசி ஓவர் பந்துவீச்சு',
    'shorts.cat_grassroots': 'அடிப்படை திறமை',
    'shorts.cat_wicketkeeping': 'விக்கெட் கீப்பிங்',
    'shorts.cat_final': 'இறுதி தருணங்கள்',

    // Athlete Digital Passport
    'athletes.badge': 'அதிகாரமளித்தல் & உள்ளடக்கம்',
    'athletes.title': 'வீரர் டிஜிட்டல் பாஸ்போர்ட் & மைக்ரோ-ஸ்பான்சர்ஷிப்',
    'athletes.desc': 'விளையாட்டு வீராங்கனைகளுக்கு நேரடியாக ரசிகர்கள் ஆதரவளித்து, உபகரணங்கள் மற்றும் பயிற்சிகளுக்கு நிதியளிக்கின்றனர்.',
    'athletes.balance': 'உங்கள் ரசிகர் இருப்பு',
    'athletes.tokens': 'ரசிகர் டோக்கன்கள்',
    'athletes.back_athlete': '50 டோக்கன்களுடன் ஆதரிக்கவும்',
    'athletes.backed_success': 'வீரர் ஆதரிக்கப்பட்டார்! +50 ஸ்பார்க்ஸ்',
    'athletes.funded': 'நிதி கிடைத்தது',
    'athletes.target': 'இலக்கு',
    'athletes.strike_rate': 'ஸ்ட்ரைக் ரேட்',
    'athletes.matches': 'போட்டிகள்',
    'athletes.wickets': 'விக்கெட்டுகள்',
    'athletes.journey': 'வீரர் பயணம்',
    'athletes.fund_purpose': 'மானிய நோக்கம்',

    // Deep RL Simulator
    'rl.badge': 'டீப் Q-லேர்னிங் & கொள்கை சாய்வு கட்டமைப்பு',
    'rl.title': 'டீப் வலுவூட்டல் கற்றல் பிட்ச் சிமுலேட்டர்',
    'rl.desc': 'ஆயிரக்கணக்கான போட்டி சூழ்நிலைகளில் பயிற்சியளிக்கப்பட்ட மார்கோவ் முடிவெடுக்கும் கொள்கைகளுடன் கேப்டன்சி உருவகப்படுத்துதல்.',
    'rl.train_step': 'RL உகப்பாக்க படியை இயக்கவும் (+50 சகாப்தங்கள்)',
    'rl.training': 'Q-கொள்கையை மேம்படுத்துகிறது...',
    'rl.episodes': 'பயிற்சி அத்தியாயங்கள்',
    'rl.reward': 'குவிந்த வெகுமதி',
    'rl.epsilon': 'ஆய்வு விகிதம் (ε)',
    'rl.confidence': 'கொள்கை நம்பிக்கை',
    'rl.optimal_action': 'பரிந்துரைக்கப்பட்ட உகந்த செயல்',
    'rl.batter_type': 'பேட்டர் சுயவிவரம்',
    'rl.bowler_type': 'பந்துவீச்சாளர் சுயவிவரம்',
    'rl.phase': 'போட்டி கட்டம்',

    // Cyber Security Shield
    'cyber.badge': 'ஜீரோ-டிரஸ்ட் பாதுகாப்பு & HMAC கிரிப்டோகிராபிக் மெஷ்',
    'cyber.title': 'சைபர் கவசம் & AI பிராம்ப்ட் பாதுகாப்பு மையம்',
    'cyber.desc': 'நேரலை ஒளிபரப்பு தரவை தீங்கிழைக்கும் ஊடுருவல் மற்றும் தரவு சிதைவுகளிலிருந்து பாதுகாக்கிறது.',
    'cyber.firewall_title': 'பிராம்ப்ட் ஊடுருவல் ஃபயர்வால்',
    'cyber.test_prompt': 'ஃபயர்வாலை சோதிக்க வினவலை உள்ளிடவும்',
    'cyber.inspect_btn': 'ஜீரோ-டிரஸ்ட் காவலருடன் ஆய்வு செய்க',
    'cyber.tamper_telemetry': 'சிதைக்கப்பட்ட தரவை உருவகப்படுத்துக',
    'cyber.restore_telemetry': 'கிரிப்டோகிராபிக் கையொப்பத்தை மீட்டமைக்கவும்',
    'cyber.clean': 'தூய்மையானது — அங்கீகரிக்கப்பட்டது',
    'cyber.blocked': 'தடுக்கப்பட்டது — அச்சுறுத்தல் கண்டறியப்பட்டது',
    'cyber.signature_valid': 'HMAC கையொப்பம் சரிபார்க்கப்பட்டது',
    'cyber.signature_invalid': 'சிதைவு கண்டறியப்பட்டது: கையொப்ப பொருத்தமின்மை',

    // User Profile
    'profile.title': 'ரசிகர் இணை-படைப்பாளர் சினாப்ஸ் சுயவிவரம்',
    'profile.handle': 'லோர்கீப்பர் ஐடி',
    'profile.sparks_balance': 'ரசிகர் ஸ்பார்க்ஸ் இருப்பு',
    'profile.credentials': 'சரிபார்க்கப்பட்ட ICC சான்றுகள்',
    'profile.achievements': 'திறக்கப்பட்ட சாதனைகள்',
    'profile.connected': 'சினாப்ஸ் இணைக்கப்பட்டது',
    'profile.logout': 'ஃபேன்வர்ஸிலிருந்து வெளியேறவும்',

    // Authentication Modal
    'auth.title': 'ஆரா லோர்கீப்பர் அணுகல்',
    'auth.subtitle': 'கிரிப்டோகிராபிக் கீபாஸ் அல்லது மின்னஞ்சல் மூலம் உள்நுழைக',
    'auth.email_label': 'படைப்பாளர் மின்னஞ்சல் அல்லது Web3 ஹேண்டில்',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'சரிபார்ப்பு மறைமுகக்குறியீட்டை உருவாக்கு',
    'auth.otp_title': '6-இலக்க சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
    'auth.otp_desc': 'உங்கள் முகவரிக்கு ஒற்றைப் பயன்பாட்டு டோக்கன் அனுப்பப்பட்டுள்ளது.',
    'auth.biometric': 'பயோமெட்ரிக் பாஸ்கீயைப் பயன்படுத்தவும்',
    'auth.verifying': 'கிரிப்டோகிராபிக் குறியீடு சரிபார்க்கப்படுகிறது...',
    'auth.success': 'அங்கீகாரம் வெற்றிகரமானது! ஃபேன்வர்ஸில் நுழைகிறது...',
    'auth.back': 'பின்செல்',
  },

  es: {
    // Nav Tabs
    'nav.discover': 'Descubrir',
    'nav.shorts': 'Shorts',
    'nav.tactical': 'IA Táctica',
    'nav.stadium3d': 'Estadio 3D',
    'nav.analytics': 'Radar',
    'nav.rl': 'Agente RL',
    'nav.cybersecurity': 'Ciberescudo',
    'nav.athletes': 'Atletas',
    'nav.profile': 'Perfil',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.sparks': 'Chispas',
    'nav.live_mesh': 'RED EN VIVO TORNEO ICC',
    'nav.over_live': 'OVER 14.3 EN VIVO',

    // 3D Stadium
    'stadium.title': 'Estadio de Críquet 3D WebGL Hiperrealista',
    'stadium.subtitle': 'Iluminación Volumétrica, Texturas Procedurales y Motor Físico',
    'stadium.desc': '4 torres de focos con conos volumétricos, césped cortado por patrones, terreno de juego desgastado y física de bails.',
    'stadium.play': 'Reproducir',
    'stadium.pause': 'Pausa',
    'stadium.reset': 'Reiniciar',
    'stadium.cam_broadcast': 'Transmisión',
    'stadium.cam_batter': 'Vista Bateador',
    'stadium.cam_hawkeye': 'Ojo de Halcón',
    'stadium.cam_topdown': 'Vista Cenital',
    'stadium.cam_stump': 'Cámara Muñón',
    'stadium.cam_drone': 'Órbita Dron',
    'stadium.cam_ballfollow': 'Seguir Pelota',
    'stadium.delivery': 'Lanzamiento:',
    'stadium.del_seam': '142 km/h Seam',
    'stadium.del_spin': '86 km/h Giro',
    'stadium.del_yorker': '148 km/h Yorker',
    'stadium.shot': 'Golpe:',
    'stadium.shot_cover': 'Cover Drive (6)',
    'stadium.shot_pull': 'Pull Shot (4)',
    'stadium.shot_straight': 'Straight Drive (4)',
    'stadium.shot_upper': 'Upper Cut (6)',
    'stadium.shot_wicket': 'Wicket ⚡',
    'stadium.lighting': 'Iluminación:',
    'stadium.light_day': 'Día',
    'stadium.light_sunset': 'Atardecer',
    'stadium.light_night': 'Noche',
    'stadium.trail': 'Trayectoria Hawk-Eye',
    'stadium.flashes': 'Flashes Multitud',
    'stadium.in_flight': 'EN EL AIRE',
    'stadium.contact_made': 'CONTACTO HECHO',
    'stadium.ready': 'LISTO',

    // Tactical AI Co-Pilot
    'tactical.badge': 'Inteligencia Táctica IA y Ensamble Multimodelo',
    'tactical.title': 'Copiloto Táctico y Estudio de Modelos IA',
    'tactical.subtitle': 'Entrenado con 2,896 partidos (7,119 estados tácticos) y 90,308 perfiles profesionales con 0.9988 ROC-AUC.',
    'tactical.tab_copilot': 'Copiloto y Radar',
    'tactical.tab_matchup': 'Matriz de Duelos',
    'tactical.tab_inplay': 'Simulador En Vivo',
    'tactical.tab_studio': 'Estudio IA y Escenarios',
    'tactical.field_radar': 'Visualizador Dinámico de Campo',
    'tactical.suggested_questions': 'Preguntas Tácticas Sugeridas por IA',
    'tactical.click_analyze': 'Clic para Analizar',
    'tactical.ask_placeholder': 'Haz una pregunta táctica...',
    'tactical.speak_guidance': 'Escuchar Guía',
    'tactical.listen_review': 'Escuchar Resumen del Over',
    'tactical.threat_high': 'AMENAZA ALTA',
    'tactical.threat_vulnerable': 'VULNERABLE',
    'tactical.threat_neutral': 'NEUTRAL',
    'tactical.threat_favorable': 'FAVORABLE',

    // Data Analytics
    'analytics.badge': 'Plataforma de Inteligencia y Big Data de Críquet',
    'analytics.title': 'Análisis de Datos, Estadísticas y Telemetría ML',
    'analytics.subtitle': 'Basado en 2,896 archivos de partidos, 90,308 registros históricos y 16,666 perfiles de jugadores.',
    'analytics.tab_data': 'Análisis de Datos',
    'analytics.tab_ml': 'Predictor ML',
    'analytics.tab_players': 'Mejores Jugadores (500)',
    'analytics.tab_matches': 'Partidos Recientes',
    'analytics.tab_charts': 'Gráficos en Vivo',
    'analytics.kpi_matches': 'Partidos Minados',
    'analytics.kpi_states': 'Estados Tácticos',
    'analytics.kpi_players': 'Registros Jugadores',
    'analytics.kpi_accuracy': 'Precisión GB',
    'analytics.kpi_t20_par': 'Promedio 1er Inns T20',
    'analytics.kpi_odi_par': 'Promedio 1er Inns ODI',
    'analytics.team_power_title': 'Equipos Mejor Calificados (ELO)',
    'analytics.phase_quantiles_title': 'Cuantiles de Anotación por Fase',
    'analytics.leaderboard_title': 'Clasificación de Impacto de Jugadores (CPI)',
    'analytics.predict_win': 'Probabilidad de Victoria',
    'analytics.projected_score': 'Puntuación Proyectada 1er Inns',
    'analytics.search_player': 'Buscar por jugador o país...',

    // General
    'common.live': 'EN VIVO',
    'common.all': 'Todos',
    'common.runs': 'Carreras',
    'common.wickets': 'Wickets',
    'common.strike_rate': 'Tasa de Golpeo',
    // Tournament Ribbon & Brand
    'ribbon.tournament': 'Final de la Copa Mundial Femenina T20 de la ICC',
    'ribbon.venue': 'Estadio Internacional de Dubái',
    'ribbon.fans_synced': '8.4M Fans Conectados en Vivo',
    'ribbon.streams': '12 Transmisiones Regionales de IA',
    'ribbon.zerotrust': 'Guardia Zero-Trust: Activo',
    'ribbon.sync_langs': '6 Idiomas Sincronizados',
    'brand.tagline': 'Canon Multimodal • Estadio 3D • Fandom en Vivo',

    // Hero Section
    'hero.badge': 'PROTOCOLO CANON GÉNESIS V2.4 • DUBAI AI SHOWCASE',
    'hero.title_pre': 'Co-Crea',
    'hero.title_gradient': 'Canon Infinito',
    'hero.title_post': 'Con IA y Tu Fandom',
    'hero.desc': 'Ingresa a un reino colaborativo etéreo donde la telemetría en vivo del críquet femenino enciende microhistorias verticales autónomas, física de estadios 3D y copiloto táctico conversacional.',
    'hero.cta_dashboard': 'Iniciar Tablero en Vivo',
    'hero.cta_auth': 'Iniciar Sesión / Acceso Lorekeeper',

    // Featured Multimodal Storyboards
    'featured.title': 'Storyboards Multimodales Destacados',
    'featured.subtitle': 'Adaptaciones autónomas de video a manga generadas en tiempo real',
    'featured.view_all': 'Ver Todos (28)',
    'featured.card1_title': 'El Espejismo de Sharjah: El Contraataque a 140 km/h de Smriti',
    'featured.card1_desc': 'Reconstruido a partir de la telemetría del over 18. Estética manga shonen con Stable Diffusion XL LoRA.',
    'featured.card1_watch': 'Ver Historia',
    'featured.card2_title': 'La Trampa en el Leg-Side de Harmanpreet: Desglose de Probabilidad',
    'featured.card2_desc': 'Análisis de aprendizaje por refuerzo Q-Learning que explica la colocación táctica ante Sophie Ecclestone.',
    'featured.card2_inspect': 'Inspeccionar Repetición',
    'featured.card3_title': "De Katmandú a Lord's: La Odisea de 5 Wickets de Puja Mahato",
    'featured.card3_desc': 'Historia financiada por la comunidad que destaca a la promesa Sub-19 de Nepal.',
    'featured.card3_tip': 'Recompensar Atleta',

    // Live Co-Creation Arenas
    'arenas.title': 'Arenas de Co-Creación en Vivo',
    'arenas.subtitle': 'Salas multijugador en tiempo real que sintetizan narrativas del partido',
    'arenas.active_badge': '3 ARENAS ACTIVAS',
    'arenas.room1_title': 'Escritores Cyber-Valkyrie',
    'arenas.room1_sub': 'Partido: IND-W vs AUS-W (Final)',
    'arenas.room1_creators': '84 Creadores',
    'arenas.room1_scene': 'Escena actual: El reverse-sweep de Harmanpreet en el over 19',
    'arenas.room2_title': 'Gremio de Análisis Táctico',
    'arenas.room2_sub': 'Geometría de Campo y Trayectorias de Giro',
    'arenas.room2_creators': '126 Creadores',
    'arenas.room2_scene': 'Escena actual: Deriva aerodinámica PINN en leg break a 62 km/h',
    'arenas.room3_title': 'Estudio Promesas Base',
    'arenas.room3_sub': 'Estrellas de Nepal, Tailandia y Escocia',
    'arenas.room3_creators': '62 Creadores',
    'arenas.room3_scene': 'Escena actual: Meta comunitaria alcanzada de 5,000 Sparks',
    'arenas.join_btn': 'Unirse a la Sesión',

    // Canon Governance Poll
    'poll.badge': 'PROPUESTA DE GOBERNANZA CANON #88',
    'poll.closes': 'CIERRA EN 04:18:22',
    'poll.title': 'Dilema Táctico: ¿Qué debe lanzar la capitana Harmanpreet en el Over 19.4?',
    'poll.desc': 'La opción ganadora determinará el clímax del anime generado y desbloqueará el doble de Sparks para los votantes.',
    'poll.opt1': 'Desplegar la trampa cuántica Googly',
    'poll.opt2': 'Mantener longitud estándar en el pasillo fuera del off-stump',
    'poll.opt3': 'Traer barrendero a la cuerda para frenar el slog sweep',
    'poll.total_votes': 'Votos totales de la comunidad: 3,489',
    'poll.sparks_reward': '+50 Sparks al Votar',

    // Multilingual AI Commentary Player
    'audio.badge': 'SÍNTESIS DE COMENTARIOS IA MULTILINGÜE',
    'audio.dialects': '12 DIALECTOS LISTOS',
    'audio.title': 'Síntesis de Voz: "El Seis Que Sacudió Sharjah"',
    'audio.desc': 'Escucha la clonación de voz neural adaptando intensidad y acústica de multitudes según la probabilidad de victoria.',
    'audio.preview': 'Escuchar Voz Neural',
    'audio.pause': 'Pausar Transmisión',
    'audio.latency': 'Latencia: 280ms',

    // Pillars of Creation
    'pillars.tag': 'Pilares de Creación',
    'pillars.title': 'Arquitectura de IA Multifilamento',
    'pillars.p1_title': 'Motor de Historias Multimodal',
    'pillars.p1_desc': 'Texto, voz, video vertical y telemetría HUD sintetizados en menos de 45 segundos.',
    'pillars.p2_title': 'Copiloto Táctico Colaborativo',
    'pillars.p2_desc': 'Desmitifica las estrategias de capitanía con IA conversacional, radar 2D y física 3D.',
    'pillars.p3_title': 'Fondo de Estrellas Futuras',
    'pillars.p3_desc': 'Los fanáticos apoyan a atletas femeninas con un 15% destinado al desarrollo de academias asociadas.',

    // Relic Codex
    'codex.tag': 'ARCHIVOS Y NODOS RELIQUIA',
    'codex.title': 'Artefactos Deportivos Canónicos y Líneas Temporales',
    'codex.total': 'Total de Artefactos: 1,420',
    'codex.card1_title': 'Rama Qué-Pasaría-Si #44',
    'codex.card1_desc': 'Historia alternativa donde Sophie Devine abrió el ataque con leg-spin.',
    'codex.card2_title': 'Reliquia de Giro Hawk-Eye',
    'codex.card2_desc': 'Token de trayectoria matemática 3D firmado por el flujo oficial ICC.',
    'codex.card3_title': 'Maestro del Over Decisivo',
    'codex.card3_desc': 'Insignia otorgada por predecir con éxito el yorker del penúltimo over.',
    'codex.card4_title': 'Nodo de Física Cuántica',
    'codex.card4_desc': 'Pruebas de redes neuronales informadas por física en cualquier entrega histórica.',

    // Community Stats
    'community.creators': 'Más de 140,000 Co-Creadores Globales',
    'community.active_desc': 'Activos en más de 850 torneos canónicos de críquet femenino',
    'community.verified': 'Libro Mayor Canónico ICC Verificado #8802',
    'community.enter': 'Entrar Ahora',

    // Shorts & Vertical Reels
    'shorts.badge': 'Canalización Autónoma Multimodal de Momentos Destacados',
    'shorts.title': 'Micro-Narrativas Verticales y Síntesis Multilingüe',
    'shorts.desc': 'Video de transmisión de la ICC transformado en reels verticales 9:16 en menos de 45 segundos con telemetría de pelota automatizada y comentarios en más de 12 idiomas.',
    'shorts.edge_ingestion': 'Ingestión en el Borde: 38s',
    'shorts.tab_shorts': '9:16 Shorts',
    'shorts.tab_long': '16:9 Transmisión',
    'shorts.exit_velocity': 'Velocidad de Salida',
    'shorts.launch_angle': 'Ángulo de Lanzamiento',
    'shorts.distance': 'Distancia',
    'shorts.win_prob_delta': 'Delta Probabilidad Victoria',
    'shorts.tactical_breakdown': 'Análisis Táctico',
    'shorts.ai_commentary': 'Comentarios Neuronales de IA',
    'shorts.play_audio': 'Escuchar en Voz',
    'shorts.stop_audio': 'Detener Voz',
    'shorts.share': 'Compartir Reel',
    'shorts.all': 'Todos',
    'shorts.cat_masterclass': 'Clase Magistral',
    'shorts.cat_pace': 'Ataque Rápido',
    'shorts.cat_clutch': 'Defensa Decisiva',
    'shorts.cat_captaincy': 'Capitanía',
    'shorts.cat_fielding': 'Fildeo',
    'shorts.cat_spin': 'Magia de Giro',
    'shorts.cat_power': 'Poder Ofensivo',
    'shorts.cat_death': 'Lanzamiento Final',
    'shorts.cat_grassroots': 'Talento de Base',
    'shorts.cat_wicketkeeping': 'Receptor',
    'shorts.cat_final': 'Momentos Finales',

    // Athlete Digital Passport
    'athletes.badge': 'Empoderamiento e Inclusión de Base',
    'athletes.title': 'Pasaporte Digital de Atletas y Centro de Micro-Patrocinio',
    'athletes.desc': 'Cerrando la brecha de financiamiento de base. Los fanáticos respaldan a las atletas directamente, obteniendo credenciales verificadas y financiando equipamiento y viajes.',
    'athletes.balance': 'Tu Saldo de Fan',
    'athletes.tokens': 'Tokens de Fan',
    'athletes.back_athlete': 'Respaldar con 50 Tokens',
    'athletes.backed_success': '¡Atleta Respaldada! +50 Sparks',
    'athletes.funded': 'Financiado',
    'athletes.target': 'Objetivo',
    'athletes.strike_rate': 'Tasa de Bateo',
    'athletes.matches': 'Partidos',
    'athletes.wickets': 'Wickets',
    'athletes.journey': 'Trayectoria',
    'athletes.fund_purpose': 'Propósito de la Beca',

    // Deep RL Simulator
    'rl.badge': 'Arquitectura de Q-Learning Profundo y Gradiente de Política',
    'rl.title': 'Simulador de Cancha de Aprendizaje por Refuerzo Profundo',
    'rl.desc': 'Simulación de decisiones de capitanía con políticas de Proceso de Decisión de Markov (MDP) entrenadas en miles de escenarios.',
    'rl.train_step': 'Ejecutar Paso de Optimización RL (+50 Épocas)',
    'rl.training': 'Optimizando Política Q...',
    'rl.episodes': 'Episodios de Entrenamiento',
    'rl.reward': 'Recompensa Acumulada',
    'rl.epsilon': 'Tasa de Exploración (ε)',
    'rl.confidence': 'Confianza de Política',
    'rl.optimal_action': 'Acción Óptima Recomendada',
    'rl.batter_type': 'Perfil de Bateadora',
    'rl.bowler_type': 'Perfil de Lanzadora',
    'rl.phase': 'Fase del Partido',

    // Cyber Security Shield
    'cyber.badge': 'Seguridad de Confianza Cero y Malla Criptográfica HMAC',
    'cyber.title': 'Escudo Cibernético y Centro de Defensa contra Inyección de IA',
    'cyber.desc': 'Protección de telemetría de transmisión en vivo y gobernanza de fanáticos contra inyecciones adversarias y manipulación de datos.',
    'cyber.firewall_title': 'Cortafuegos contra Inyección de Prompts',
    'cyber.test_prompt': 'Consulta de prueba para el cortafuegos',
    'cyber.inspect_btn': 'Inspeccionar con Guardia de Confianza Cero',
    'cyber.tamper_telemetry': 'Simular Telemetría Manipulada',
    'cyber.restore_telemetry': 'Restaurar Firma Criptográfica',
    'cyber.clean': 'LIMPIO — AUTENTICADO',
    'cyber.blocked': 'BLOQUEADO — AMENAZA ADVERSARIA DETECTADA',
    'cyber.signature_valid': 'Firma Criptográfica HMAC Verificada',
    'cyber.signature_invalid': 'MANIPULACIÓN DETECTADA: Discrepancia de Firma',

    // User Profile
    'profile.title': 'Perfil de Sinapsis del Co-Creador',
    'profile.handle': 'ID de Guardián del Canon',
    'profile.sparks_balance': 'Saldo de Chispas de Fan',
    'profile.credentials': 'Credenciales Verificadas de la ICC',
    'profile.achievements': 'Logros Desbloqueados',
    'profile.connected': 'Sinapsis Conectada',
    'profile.logout': 'Cerrar Sesión de FanVerse',

    // Authentication Modal
    'auth.title': 'Acceso para Guardianes AURA',
    'auth.subtitle': 'Inicie sesión con pase criptográfico o verificación por correo',
    'auth.email_label': 'Correo de Creador o Identificador Web3',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'Generar Cifra de Verificación',
    'auth.otp_title': 'Ingrese Cifra de 6 Dígitos',
    'auth.otp_desc': 'Se envió un token criptográfico de un solo uso a su identificador.',
    'auth.biometric': 'Usar Llave de Acceso Biométrica',
    'auth.verifying': 'Verificando Cifra Criptográfica...',
    'auth.success': '¡Autenticación Verificada! Ingresando a FanVerse...',
    'auth.back': 'Volver',
  },

  ar: {
    // Nav Tabs
    'nav.discover': 'اكتشف',
    'nav.shorts': 'فيديوهات قصيرة',
    'nav.tactical': 'الذكاء التكتيكي',
    'nav.stadium3d': 'ملعب 3D',
    'nav.analytics': 'الرادار',
    'nav.rl': 'وكيل RL',
    'nav.cybersecurity': 'الدرع السيبراني',
    'nav.athletes': 'الرياضيون',
    'nav.profile': 'الملف الشخصي',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.sparks': 'سباركس',
    'nav.live_mesh': 'شبكة بطولة ICC المباشرة',
    'nav.over_live': 'الشوط 14.3 مباشر',

    // 3D Stadium
    'stadium.title': 'ملعب الكريكيت ثلاثي الأبعاد الواقعي',
    'stadium.subtitle': 'إضاءة حجمية ومواد إجرائية وفيزياء متقدمة',
    'stadium.desc': '4 أبراج إضاءة مع مخاريط حجمية، عشب مخطط إجرائياً، ملعب طيني، شاشات رقمية متحركة.',
    'stadium.play': 'تشغيل',
    'stadium.pause': 'إيقاف مؤقت',
    'stadium.reset': 'إعادة ضبط',
    'stadium.cam_broadcast': 'بث تلفزيوني',
    'stadium.cam_batter': 'منظور الضارب',
    'stadium.cam_hawkeye': 'عين الصقر',
    'stadium.cam_topdown': 'منظر علوي',
    'stadium.cam_stump': 'كاميرا المرمى',
    'stadium.cam_drone': 'مدار الطائرة بدون طيار',
    'stadium.cam_ballfollow': 'تتبع الكرة',
    'stadium.delivery': 'الرمية:',
    'stadium.del_seam': '142 كم/س درز',
    'stadium.del_spin': '86 كم/س دوران',
    'stadium.del_yorker': '148 كم/س يوركر',
    'stadium.shot': 'الضربة:',
    'stadium.shot_cover': 'ضربة التغطية (6)',
    'stadium.shot_pull': 'ضربة السحب (4)',
    'stadium.shot_straight': 'ضربة مستقيمة (4)',
    'stadium.shot_upper': 'ضربة علوية (6)',
    'stadium.shot_wicket': 'سقوط ويكيت ⚡',
    'stadium.lighting': 'الإضاءة:',
    'stadium.light_day': 'نهار',
    'stadium.light_sunset': 'غروب',
    'stadium.light_night': 'ليل',
    'stadium.trail': 'مسار عين الصقر',
    'stadium.flashes': 'فلاشات الجماهير',
    'stadium.in_flight': 'في الهواء',
    'stadium.contact_made': 'تم الاتصال',
    'stadium.ready': 'جاهز',

    // Tactical AI Co-Pilot
    'tactical.badge': 'الذكاء التكتيكي ومجموعة النماذج المتعددة',
    'tactical.title': 'المساعد التكتيكي واستوديو نماذج الذكاء الاصطناعي',
    'tactical.subtitle': 'مدرب على 2,896 مباراة (7,119 حالة تكتيكية) و90,308 ملف للاعبين بمعيار 0.9988 ROC-AUC.',
    'tactical.tab_copilot': 'المساعد التكتيكي والرادار',
    'tactical.tab_matchup': 'مصفوفة المواجهات',
    'tactical.tab_inplay': 'محاكي الفوز المباشر',
    'tactical.tab_studio': 'استوديو الذكاء الاصطناعي',
    'tactical.field_radar': 'خريطة توزيع الميدان التفاعلية',
    'tactical.suggested_questions': 'أسئلة تكتيكية مقترحة',
    'tactical.click_analyze': 'انقر للتحليل',
    'tactical.ask_placeholder': 'اطرح سؤالاً تكتيكياً...',
    'tactical.speak_guidance': 'استمع للتوجيه',
    'tactical.listen_review': 'استمع لمراجعة الشوط',
    'tactical.threat_high': 'تهديد مرتفع',
    'tactical.threat_vulnerable': 'معرض للخطر',
    'tactical.threat_neutral': 'محايد',
    'tactical.threat_favorable': 'مناسب',

    // Data Analytics
    'analytics.badge': 'منصة تحليلات البيانات الضخمة للكريكيت',
    'analytics.title': 'تحليل البيانات، إحصائيات المباريات وقياس التعلم الآلي',
    'analytics.subtitle': 'مبني على 2,896 ملف مباراة، 90,308 سجل للاعبين، و16,666 ملف شخصي.',
    'analytics.tab_data': 'تحليل البيانات',
    'analytics.tab_ml': 'متنبئ الفوز',
    'analytics.tab_players': 'أفضل اللاعبين (500)',
    'analytics.tab_matches': 'المباريات الأخيرة',
    'analytics.tab_charts': 'مخططات حية',
    'analytics.kpi_matches': 'المباريات المحللة',
    'analytics.kpi_states': 'الحالات التكتيكية',
    'analytics.kpi_players': 'سجلات اللاعبين',
    'analytics.kpi_accuracy': 'دقة GB',
    'analytics.kpi_t20_par': 'معدل الشوط الأول T20',
    'analytics.kpi_odi_par': 'معدل الشوط الأول ODI',
    'analytics.team_power_title': 'الفرق الأعلى تقييماً (ELO)',
    'analytics.phase_quantiles_title': 'توقعات تسجيل النقاط حسب المرحلة',
    'analytics.leaderboard_title': 'لوحة صدارة تأثير اللاعبين (CPI)',
    'analytics.predict_win': 'احتمال الفوز',
    'analytics.projected_score': 'النقاط المتوقعة للشوط الأول',
    'analytics.search_player': 'البحث حسب اللاعب أو الدولة...',

    // General
    'common.live': 'مباشر',
    'common.all': 'الكل',
    'common.runs': 'الركضات',
    'common.wickets': 'الويكيت',
    'common.strike_rate': 'معدل الضرب',
    // Tournament Ribbon & Brand
    'ribbon.tournament': 'نهائي كأس العالم للسيدات T20 للمجلس الدولي للكريكيت',
    'ribbon.venue': 'استاد دبي الدولي',
    'ribbon.fans_synced': '8.4M مشجع متصلون مباشرة',
    'ribbon.streams': '12 بث إقليمي للذكاء الاصطناعي',
    'ribbon.zerotrust': 'درع انعدام الثقة: نشط',
    'ribbon.sync_langs': '6 لغات متزامنة',
    'brand.tagline': 'كانون متعدد الوسائط • ملعب ثلاثي الأبعاد • جماهير مباشرة',

    // Hero Section
    'hero.badge': 'بروتوكول كانون جينيسيس V2.4 • معرض دبي للذكاء الاصطناعي',
    'hero.title_pre': 'شارك في إنشاء',
    'hero.title_gradient': 'الكانون اللانهائي',
    'hero.title_post': 'مع الذكاء الاصطناعي وعشاق الرياضة',
    'hero.desc': 'ادخل إلى عالم تعاوني أثيري حيث تحفز بيانات الكريكيت النسائية الحية القصص المصغرة العمودية المستقلة وفيزياء الملاعب ثلاثية الأبعاد والمساعد التكتيكي الذكي.',
    'hero.cta_dashboard': 'إطلاق لوحة التحكم المباشرة',
    'hero.cta_auth': 'تسجيل الدخول / وصول حارس المعرفة',

    // Featured Multimodal Storyboards
    'featured.title': 'لوحات القصص المميزة متعددة الوسائط',
    'featured.subtitle': 'اقتباسات تلقائية من الفيديو إلى المانجا تم إنشاؤها في الوقت الفعلي',
    'featured.view_all': 'عرض الكل (28)',
    'featured.card1_title': 'سراب الشارقة: هجوم سمريتي المضاد بسرعة 140 كم/ساعة',
    'featured.card1_desc': 'أعيد بناؤها من القياسات عن بعد للشوط 18. أسلوب شونين مانجا تم إنشاؤه بواسطة Stable Diffusion XL مع تعليق صوتي.',
    'featured.card1_watch': 'مشاهدة القصة',
    'featured.card2_title': 'فخ هارمانبريت الجانبي: تحليل الاحتمالات',
    'featured.card2_desc': 'تحليل التعلم المعزز العميق الذي يوضح تمركز اللاعبات الميداني ضد صوفي إكليستون.',
    'featured.card2_inspect': 'فحص الإعادة',
    'featured.card3_title': 'من كاتماندو إلى لوردز: ملحمة بوجا ماهاتو مع 5 ويكيت',
    'featured.card3_desc': 'قصة بتمويل مجتمعي تسلط الضوء على رامية نيبال السريعة تحت 19 سنة.',
    'featured.card3_tip': 'مكافأة اللاعبة',

    // Live Co-Creation Arenas
    'arenas.title': 'ساحات الإنشاء المشترك المباشرة',
    'arenas.subtitle': 'غرف متعددة اللاعبين في الوقت الفعلي تصنع روايات المباريات',
    'arenas.active_badge': '3 ساحات نشطة',
    'arenas.room1_title': 'كتاب فالكيري السيبرانيون',
    'arenas.room1_sub': 'المباراة: سيدات الهند ضد سيدات أستراليا (النهائي)',
    'arenas.room1_creators': '84 صانع محتوى',
    'arenas.room1_scene': 'المشهد الحالي: تسديدة هارمانبريت العكسية في الشوط 19',
    'arenas.room2_title': 'نقابة التحليل التكتيكي',
    'arenas.room2_sub': 'هندسة الميدان ومسارات الدوران',
    'arenas.room2_creators': '126 صانع محتوى',
    'arenas.room2_scene': 'المشهد الحالي: الانجراف الهوائي الفيزيائي للكرة بسرعة 62 كم/ساعة',
    'arenas.room3_title': 'استوديو تسليط الضوء على المواهب الصاعدة',
    'arenas.room3_sub': 'نجمات نيبال وتايلاند واسكتلندا',
    'arenas.room3_creators': '62 صانع محتوى',
    'arenas.room3_scene': 'المشهد الحالي: تمويل جماعي وصل إلى 5000 شرارة',
    'arenas.join_btn': 'الانضمام إلى الجلسة',

    // Canon Governance Poll
    'poll.badge': 'اقتراح حوكمة الكانون #88',
    'poll.closes': 'ينتهي خلال 04:18:22',
    'poll.title': 'معضلة تكتيكية: ما الذي يجب أن ترميه الكابتن هارمانبريت في الشوط 19.4؟',
    'poll.desc': 'الخيار الفائز سيحدد ذروة الأنمي المولدة ويفتح شرارات مضاعفة للمشاركين.',
    'poll.opt1': 'نصب فخ غوغلي الكمي',
    'poll.opt2': 'الحفاظ على طول قياسي خارج الويكيت',
    'poll.opt3': 'جلب لاعبة ميدان لحماية الحدود من الضربة القوية',
    'poll.total_votes': 'إجمالي أصوات المجتمع: 3,489',
    'poll.sparks_reward': '+50 شرارة عند التصويت',

    // Multilingual AI Commentary Player
    'audio.badge': 'توليف التعليق الصوتي للذكاء الاصطناعي متعدد اللغات',
    'audio.dialects': '12 لهجة جاهزة',
    'audio.title': 'توليف الصوت: "الضربة السداسية التي هزت الشارقة"',
    'audio.desc': 'استمع إلى استنساخ الصوت العصبي الذي يكيف النبرة وهتاف الجماهير ديناميكياً مع تغير احتمالية الفوز.',
    'audio.preview': 'معاينة الصوت العصبي',
    'audio.pause': 'إيقاف البث مؤقتاً',
    'audio.latency': 'زمن الاستجابة: 280 مللي ثانية',

    // Pillars of Creation
    'pillars.tag': 'ركائز الإبداع',
    'pillars.title': 'بنية ذكاء اصطناعي متعددة المسارات',
    'pillars.p1_title': 'محرك القصص متعدد الوسائط',
    'pillars.p1_desc': 'نصوص وتعليقات صوتية وفيديو رأسي وبيانات حية يتم توليدها في أقل من 45 ثانية.',
    'pillars.p2_title': 'المساعد التكتيكي التعاوني',
    'pillars.p2_desc': 'يوضح استراتيجيات قيادة الفريق باستخدام الذكاء الاصطناعي والرادار ثنائي الأبعاد والفيزياء ثلاثية الأبعاد.',
    'pillars.p3_title': 'صندوق نجوم المستقبل الصاعدين',
    'pillars.p3_desc': 'يتعهد المشجعون برموز صغيرة للاعبات مع تخصيص 15% لدعم الأكاديميات في الدول الناشئة.',

    // Relic Codex
    'codex.tag': 'الأرشيف وعقد الآثار',
    'codex.title': 'الآثار الرياضية التاريخية وخطوط الزمن',
    'codex.total': 'إجمالي الآثار: 1,420',
    'codex.card1_title': 'فرع ماذا لو #44',
    'codex.card1_desc': 'تاريخ بديل حيث بدأت صوفي ديفين الرمي بالدوران الجانبي.',
    'codex.card2_title': 'أثر دوران عين الصقر',
    'codex.card2_desc': 'رمز مسار رياضي ثلاثي الأبعاد معتمد من المجلس الدولي للكريكيت.',
    'codex.card3_title': 'بطل الشوط الحاسم',
    'codex.card3_desc': 'شارة تُمنح للتوقع الصحيح لرمية الويكيت في الشوط قبل الأخير.',
    'codex.card4_title': 'عقدة فيزياء الكم',
    'codex.card4_desc': 'إجراء اختبارات الشبكات العصبية المعتمدة على الفيزياء على أي رمية تاريخية.',

    // Community Stats
    'community.creators': 'أكثر من 140,000 صانع محتوى عالمي',
    'community.active_desc': 'نشطون في أكثر من 850 بطولة ورواية كريكيت نسائية',
    'community.verified': 'سجل كانون المعتمد من ICC #8802',
    'community.enter': 'دخول الآن',

    // Shorts & Vertical Reels
    'shorts.badge': 'خط إنتاج اللقطات البارزة متعدد الوسائط',
    'shorts.title': 'قصص مصغرة رأسية وتوليف صوتي متعدد اللغات',
    'shorts.desc': 'تحويل فيديو بث ICC المباشر إلى مقاطع رأسية 9:16 في أقل من 45 ثانية مع بيانات تتبع الكرة والتعليق بأكثر من 12 لغة.',
    'shorts.edge_ingestion': 'معالجة الحافة: 38 ثانية',
    'shorts.tab_shorts': 'مقاطع قصيرة 9:16',
    'shorts.tab_long': 'بث مباشر 16:9',
    'shorts.exit_velocity': 'سرعة الانطلاق',
    'shorts.launch_angle': 'زاوية الانطلاق',
    'shorts.distance': 'المسافة',
    'shorts.win_prob_delta': 'تغير احتمالية الفوز',
    'shorts.tactical_breakdown': 'التحليل التكتيكي',
    'shorts.ai_commentary': 'تعليق الذكاء الاصطناعي العصبي',
    'shorts.play_audio': 'استمع بالصوت',
    'shorts.stop_audio': 'إيقاف الصوت',
    'shorts.share': 'مشاركة المقطع',
    'shorts.all': 'الكل',
    'shorts.cat_masterclass': 'درس متقدم',
    'shorts.cat_pace': 'هجوم سريع',
    'shorts.cat_clutch': 'دفاع حاسم',
    'shorts.cat_captaincy': 'القيادة',
    'shorts.cat_fielding': 'حراسة الميدان',
    'shorts.cat_spin': 'سحر الدوران',
    'shorts.cat_power': 'ضربات قوية',
    'shorts.cat_death': 'رميات الأشواط الأخيرة',
    'shorts.cat_grassroots': 'مواهب واعدة',
    'shorts.cat_wicketkeeping': 'حراسة الويكيت',
    'shorts.cat_final': 'اللحظات الأخيرة',

    // Athlete Digital Passport
    'athletes.badge': 'التمكين والشمولية المجتمعية',
    'athletes.title': 'جواز السفر الرقمي للاعبة ومنصة الرعاية المصغرة',
    'athletes.desc': 'سد فجوة التمويل الرياضي. يدعم المشجعون الرياضيات مباشرة مع تمويل المعدات والسفر والمعسكرات التدريبية.',
    'athletes.balance': 'رصيد المشجع الخاص بك',
    'athletes.tokens': 'رموز المشجعين',
    'athletes.back_athlete': 'ادعم بـ 50 رمزاً',
    'athletes.backed_success': 'تم دعم اللاعبة! +50 شرارة',
    'athletes.funded': 'تم التمويل',
    'athletes.target': 'الهدف',
    'athletes.strike_rate': 'معدل الضربات',
    'athletes.matches': 'المباريات',
    'athletes.wickets': 'الويكيت',
    'athletes.journey': 'مسيرة اللاعبة',
    'athletes.fund_purpose': 'الغرض من المنحة',

    // Deep RL Simulator
    'rl.badge': 'بنية التعلم المعزز العميق Q-Learning وتدرج السياسات',
    'rl.title': 'محاكي رميات التعلم المعزز العميق',
    'rl.desc': 'محاكاة قرارات القيادة التكتيكية باستخدام سياسات عمليات اتخاذ القرار لماركوف (MDP) المدربة على آلاف سيناريوهات المباريات.',
    'rl.train_step': 'تشغيل خطوة تحسين RL (+50 دورة)',
    'rl.training': 'تحسين سياسة Q جارية...',
    'rl.episodes': 'حلقات التدريب',
    'rl.reward': 'المكافأة التراكمية',
    'rl.epsilon': 'معدل الاستكشاف (ε)',
    'rl.confidence': 'ثقة السياسة',
    'rl.optimal_action': 'الإجراء الأمثل الموصى به',
    'rl.batter_type': 'ملف الضاربة',
    'rl.bowler_type': 'ملف الرامية',
    'rl.phase': 'مرحلة المباراة',

    // Cyber Security Shield
    'cyber.badge': 'أمان انعدام الثقة والشبكة المشفرة HMAC',
    'cyber.title': 'الدرع السيبراني ومركز الدفاع ضد هجمات الذكاء الاصطناعي',
    'cyber.desc': 'حماية بيانات البث في الوقت الفعلي وحوكمة الجماهير من حقن الأوامر الضارة والتلاعب بالبيانات.',
    'cyber.firewall_title': 'جدار حماية ضد حقن الأوامر',
    'cyber.test_prompt': 'أدخل استعلاماً لاختبار جدار الحماية',
    'cyber.inspect_btn': 'فحص بواسطة حارس انعدام الثقة',
    'cyber.tamper_telemetry': 'محاكاة بيانات متلاعب بها',
    'cyber.restore_telemetry': 'استعادة التوقيع المشفر',
    'cyber.clean': 'سليم — موثق',
    'cyber.blocked': 'محظور — تم اكتشاف تهديد ضار',
    'cyber.signature_valid': 'تم التحقق من توقيع HMAC المشفر',
    'cyber.signature_invalid': 'تم اكتشاف تلاعب: عدم تطابق التوقيع',

    // User Profile
    'profile.title': 'الملف الشخصي للمشارك المشجع',
    'profile.handle': 'معرف حارس الكانون',
    'profile.sparks_balance': 'رصيد شرارات المشجع',
    'profile.credentials': 'شهادات ICC المعتمدة',
    'profile.achievements': 'الإنجازات المفتوحة',
    'profile.connected': 'المشتبك متصل',
    'profile.logout': 'تسجيل الخروج من FanVerse',

    // Authentication Modal
    'auth.title': 'دخول حراس أورا',
    'auth.subtitle': 'سجل الدخول باستخدام المفتاح المشفر أو التحقق بالبريد',
    'auth.email_label': 'بريد المبدع أو معرف Web3',
    'auth.email_placeholder': 'lorekeeper@auraverse.io',
    'auth.send_code': 'إنشاء شفرة التحقق',
    'auth.otp_title': 'أدخل شفرة التحقق المكونة من 6 أرقام',
    'auth.otp_desc': 'تم إرسال رمز مشفر للاستخدام لمرة واحدة إلى معرفك.',
    'auth.biometric': 'استخدام مفتاح المرور البيومتري',
    'auth.verifying': 'جاري التحقق من الشفرة المشفرة...',
    'auth.success': 'تم التحقق من المصادقة! جاري الدخول إلى FanVerse...',
    'auth.back': 'رجوع',
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
  dir: 'ltr' | 'rtl';
  currentOption: LanguageOption;
  getSpeechLangCode: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('aura_fanverse_lang');
    if (saved && ['en', 'hi', 'te', 'ta', 'es', 'ar'].includes(saved)) {
      return saved as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('aura_fanverse_lang', lang);
    const opt = SUPPORTED_LANGUAGES.find((l) => l.code === lang);
    document.documentElement.dir = opt?.dir || 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    const opt = SUPPORTED_LANGUAGES.find((l) => l.code === language);
    document.documentElement.dir = opt?.dir || 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, defaultText?: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || defaultText || key;
  };

  const currentOption = SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  const getSpeechLangCode = (): string => {
    switch (language) {
      case 'hi': return 'hi-IN';
      case 'te': return 'te-IN';
      case 'ta': return 'ta-IN';
      case 'es': return 'es-ES';
      case 'ar': return 'ar-SA';
      default: return 'en-US';
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: currentOption.dir, currentOption, getSpeechLangCode }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
